########################################
# 업무 프라퍼티 설정 영역
########################################

#이중 로그인체크 허용여부 Y:허용, N:불가
ALLOW_DUPLICATE_LOGIN = Y

########################################
#BCP 관련 프로퍼티
#10.61.17.101	개발
#211.32.160.65	BCP IP변경
#10.61.11.150	운영
########################################
# BCPDecryptService_ip=10.61.17.101
# BCPDecryptService_port=20005
# BCPDecryptService_characterSet=EUC-KR
# BCPDecryptService_timeout=300000

#SCNF사용 SIT/UAT : N, REAL:Y
# IS_REAL = N

HOMEBRANCH = 0019

AGENTBRANCH = 0019

SUBTASKCODE = 0001

########################################
#전문 관련
########################################
# 호스트 연속거래 최대 반복 개수
# HOST_MAP_LOOP = 15

# MCI 연속거래 최대 반복 개수
# MCI_MAP_LOOP = 15

#SCNF사용  변경 금지! 숫자2자리는 해외체류사실 조회 전문번호 채번시 WAS 고유식별번호로 사용
# MCI_TMSG_CRE_SYS_NM = NF01
# MCI_TMSG_CRE_SYS_NM[MA31101] = NF01
# MCI_TMSG_CRE_SYS_NM[CSL1101] = NF01
# MCI_TMSG_CRE_SYS_NM[PMS1101] = NF01

#SCNF사용 SIT/UAT, REAL 구분 필요
# MCI_IPV6_ADR = 10.61.17.91
# MCI_IPV6_ADR[MA31101] = 10.61.17.91
# MCI_IPV6_ADR[CSL1101] = 10.61.17.91
# MCI_IPV6_ADR[PMS1101] = 10.61.17.91

#SCNF사용 D:개발,S:SIT,U:UAT,R:운영
# MCI_ENVR_INFO_DV_CD = S

# MCI_TRAN_SEQ_PATH = /APP/mobile_SIT/ROOT.war/resource/common/seq/

########################################
# EDMI 전문 공통
########################################
# EDMI_TMSG_CRE_SYS_NM = NF01
# EDMI_TMSG_CRE_SYS_NM[MA31101] = NF01
# EDMI_TMSG_CRE_SYS_NM[CSL1101] = NF01
# EDMI_TMSG_CRE_SYS_NM[PMS1101] = NF01

# EDMI_IPV6_ADR = 10.61.17.91
# EDMI_IPV6_ADR[MA31101] = 10.61.17.91
# EDMI_IPV6_ADR[CSL1101] = 10.61.17.91
# EDMI_IPV6_ADR[PMS1101] = 10.61.17.91

#SCNF사용 D:개발,S:SIT,U:UAT,R:운영
# EDMI_ENVR_INFO_DV_CD = S
# EDMI_TRAN_SEQ_PATH = /APP/mobile_SIT/ROOT.war/resource/common/seq/
# EDMI_MAP_LOOP = 15

########################################
# Syncat 서비스
########################################
SYNCAT_GW_IP = 10.61.222.42
SYNCAT_GW_PORT = 20000

########################################
# SMS 서비스
########################################
sms.server.ip = 194.168.1.27
sms.server.port = 9090
lms.server.port = 9192

########################################
# PKI모듈 관련
########################################
PKI_TIME_URL = /bsoi/commons/nonceTime?action=time
PKI_COPY_URL = /bsoi/commons/certRelay
VPCG_AGENT_URL = /bsoi/commons/vpcgAgent
VPCG_APP_URL = /resource/product/wizvera/delfino/delfinoApp.html
CRT_TermGijun = M
CRT_TermPeriod = 1
CRT_fincertTermPeriod = 3
CRT_kfbTermPeriod = 30
CRT_YESSIGN_CAIP = 203.233.91.231
CRT_YESSIGN_CAPORT = 4512
CRT_RegiBranchNum = 860
#CRT_yesDN1=CN=yessignCA-Test Class 2, OU=AccreditedCA, O=yessign, C=kr
#CRT_yesDN2=CN=yessignCA-Test Class 3, OU=AccreditedCA, O=yessign, C=kr
#CRT_yesDN3=CN=yessignCA-TEST, OU=AccreditedCA, O=yessign, C=kr
#CRT_yesDN4=CN=yessignCA-Test Class 4, OU=AccreditedCA, O=yessign, C=kr
CRT_CertConfigPath = /APP/product/initech/mobile/iniplugin/properties/CertConfig.properties
CRT_SG_REG_IB_RANCH_NUM = 860
CRT_SG_POLICYID_P = 1 등급 인증서(개인)
CRT_SG_POLICYID_C = 1 등급 인증서(법인)
##CRT_RaServer = 10.61.157.134
CRT_RaServer = 10.61.157.141
# INITECH_PROPERTIES_JCERTOID_PATH = /APP/product/initech/mobile_sit/iniplugin/properties/jCERTOID.properties
# INITECH_PROPERTIES_INISAFESIGN_PATH = /APP/product/initech/mobile_sit/iniplugin/properties/INISAFESign.properties
INITECH_PROPERTIES_OCSPGD_PATH = /APP/product/initech/mobile/iniplugin/properties/jOCSPGD.properties
INITECH_PROPERTIES_OPPRA_PATH = /APP/product/initech/mobile/iniplugin/properties/jOPPRA.properties
# INITECH_CA_FILTER=Test

########################################
# 전자서명 설정
########################################
SDTA_TYPE = D
SYS_NAME = MA30
# SIGN_DIR = /signdata/stores
# SIGN_DIR_BACKUP = /signdata/stores/backup
INITECH_INISAFENET_PATH=/APP/product/initech/mobile/inisafenet/properties/INISAFENet.properties
# INITECH_CERT_SYNC_PATH=/APP/product/initech/mobile_sit/certsync/properties/INISAFENet.properties

########################################
#인증서가져오기/내보내기 as-is:0, ut:1, sit:2, uat:3
########################################
# GET_CERT_THIS_SERVER_INDEX = 2
# GET_CERT_SERVER_URL1 = http://10.61.157.133:9081/common/jsp/GetCertificate_v12.jsp
# GET_CERT_SERVER_URL2 = http://10.61.17.91:8690/product/pki/GetCertificate_v12.jsp
# GET_CERT_SERVER_URL3 = http://10.61.17.91:8700/product/pki/GetCertificate_v12.jsp
# GET_CERT_SERVER_URL4 = http://10.61.17.91:8710/product/pki/GetCertificate_v12.jsp

# GET_CERT_THIS_SERVER_INDEX_MA30101 = 1
# GET_CERT_THIS_SERVER_INDEX_MA31101 = 2
# GET_CERT_THIS_SERVER_INDEX_MA32101 = 3

########################################
# 스마트오퍼
########################################
# sobroker.recommendURL = http://10.61.157.136:9070/so/recommend
# sobroker.timeout = 10000

########################################
# 실명인증
########################################
# NAMECHECK_IP = 10.61.157.26
# NAMECHECK_PORT = 19000
# CARD_24365_TIME = 800
#SIT , UAT는 Y , REAL은 N ( 테스트계 실명인증은 무조건 ByPassFlag
# TESTNAMECHKFLAG = Y

########################################
# 블록체인(뱅크사인)
########################################
# BCNS_URL = http://10.61.17.184:8980;
# KFB_SIGN_VERIFY_LIC_PATH=/APP/product/kfbsign/jcaos.lic

########################################
#[2018.12.06] bill SMTP 정보
########################################
SMTP_OUTLOOK_USE = Y
SMTP_OUTLOOK_IP = 10.61.20.22
SMTP_OUTLOOK_PORT = 25
SMTP_OUTLOOK_SENDER = BB119Helpdesk
SMTP_OUTLOOK_DOMAIN = @scfirstbank.com

########################################
#[2021.04.02] 통합대출 SMTP 정보
########################################
# SMTP_OUTLOOK_PL_NOTICE_USE = Y
# SMTP_OUTLOOK_PL_NOTICE_SENDER = SCBK.PL_NOTICE
# SMTP_OUTLOOK_PL_NOTICE_DOMAIN = @sc.com

########################################
# 메일서버
# 변경전(23.20.12.171) -> 변경후(10.61.17.236)
# 2020-11-17 IT요청 ut, sit imas ip변경 (10.61.17.30) , 포트동일
########################################
IMAS_IP = 10.61.17.30
IMAS_PORT = 9100

########################################
# CONGNAMUL(영업점찾기)
########################################
# CONGNAMUL_IP = 10.61.157.26
# CONGNAMUL_PORT = 18000

########################################
# nfilter BCP 위치는 나중에 수정 필요함.
########################################
#NFILTER_PROPERTIES_PATH=/smbank/SMBank_app.ear/SMBankWeb.war/WEB-INF/nfilter.properties
# NFILTER_PROPERTIES_PATH =/APP/product/OpenWebnFilter/mobile_SIT/config/nfilter.properties

########################################
# Clip설정
########################################
CLIP_REPORT_URL=https://clipsit.standardchartered.co.kr/clip/
LOAN_CLIP_REPORT_URL=https://clipsit.standardchartered.co.kr/clip/
# EDOC_SELFBANK_REPO=/scnf/tscnf_sit.ear/obibWeb.war/WEB-INF/clipreport4/pdf/
# EDOC_SELFBANK_REPO_WAS=/APP/mobile_SIT/ROOT.war/edoc/loan/clipreport4/pdf/
# EDOC_LOAN_SIGN_PDF_WAS=/APP/PDF/MB30/edoc/loan/clipreport4/pdf/
# FILE_SYNC_PROPERTIES_PATH=/APP/mobile_SIT/ROOT.war/WEB-INF/classes/cfg/properties/FilesyncClient.properties
# BANCA_HTML_PATH=/APP/mobile_SIT/ROOT.war/edoc/banca/
# BANCA_HTML_URL=https://ma3sit.standardchartered.co.kr/edoc/banca/
# EDOC_FUND_PATH=/APP/mobile_SIT/ROOT.war/edoc/fund/
# EDOC_OBIB_REPO=/obib/obib_dev.ear/obibWeb.war/WEB-INF/clipreport4/pdf/BR/

#서버 IP
# SIGN_WAS_IP=10.61.17.91

#전자문서 중계서버
EDOC_RELAY_SERVER_URL_1=http://10.61.17.198:8580
EDOC_RELAY_SERVER_URL_2=http://10.61.17.198:8680
EDOC_RELAY_SERVER_URL_ACTION=/EdocCommonBizService.act

#EDOC 1서버 SCP 전송여부 확인
EDOC_CHECK_SCP_PATH1 = http://10.61.17.198:8580/EdocCommonBizService.act
#EDOC 2서버 SCP 전송여부 확인
EDOC_CHECK_SCP_PATH2 = http://10.61.17.198:8580/EdocCommonBizService.act


#KTNET
# KTNET_PROP_ROOT=/APP/product/ktnet
# KTNET_PROP_PATH=/APP/product/ktnet/config/tradesign3280.properties
# KTNET_CERT_PATH=/APP/product/ktnet/config/ServerCert/signCert.der
# KTNET_PRIV_PATH=/APP/product/ktnet/config/ServerCert/signPri.key
# KTNET_PRIV_SECRET=asdfasdf

########################################
# Homepage URL	// REAL -> [www] 적용부탁드립니다.
########################################
HOMEPAGE_URL=https://owwwsit.standardchartered.co.kr

#MA30 URL
MA30_URL=https://ma3sit.standardchartered.co.kr

#시스템 전환 시간.
S_CK_TIME=2355,0020
#페이지체크 무시 URI (구분자는 |)
#PAGECHECK_IGNORE_URI_LIST=/common/MA3CMMINF001_100S.act|/common/MA3CMMERR001.mnu|/common/MA3CMMINF003_100S.act|/custcenter/MA3CSTSTI004.mnu
PAGECHECK_IGNORE_URI_LIST=/process/api/v1/common/functions/authority/checkMenuInfo|/process/api/v1/common/functions/holiday/list|/process/api/v1/common/settings/app/getInitInfo|/process/api/v1/common/settings/code/list|/process/api/v1/customer/info/login/inquirySessionInfo
#페이지체크 무시 메뉴ID (구분자는 |)
PAGECHECK_IGNORE_MENU_ID = COMCMP004_01MS|COMCMP004_02MS|COMCMP004_03MS|SVCSUP003|MA3CSTSTI004|COMETC000

#default사용자정보
# DEFAULT_BRANCHNO=860

#Raon Service Info
RAON_ADAPTER_IP=10.61.17.198
RAON_ADAPTER_PORT=7035
RAON_ADAPTER_TIMEOUT=10000
RAON_CUST_ID=9999E17A6143115164A5
# RAON_SERVICE_ID=161F3A85927B32A50810

#실명인증
# KOREA_TRUST_WORKTYPE=checkKoreaTrustCheck
# KOREA_TRUST_ADD_KEY=80421577

########################################
#ClickToCall Info
########################################
clickToCall.server.ip=10.61.13.204
clickToCall.server.port=10010

########################################
#SSO
########################################
SSO_SERVER_URL=http://pkisso.standardchartered.co.kr:6480

########################################
#pongift 선물하기
########################################
PON_GIFT_URL=https://dev.pongift.com/scpaytest?

#########################################
# 펀드 PDF
#########################################
# 사용여부 판단 필요
PMS_FILE_ROOT=/APP/mpms_SIT/ROOT.war

#########################################
# FIDO(RAON, ONEPASS)
#########################################
FIDO_SERVER_DOMAIN=http://10.61.17.91:8890/fido/interfBiz/processRequest.do
FIDO_SERVER_TIMEOUT=10000
FIDO_SITE_ID=SIT01SCBANK000000000
FIDO_SVC_ID=SVC01SCBANK000000000


#########################################
# PMS 이미지 경로
#########################################
PMS_RESOURCE_ROOT = https://ma3ut.standardchartered.co.kr/mpms_RESOURCE
PMS_IMG_ROOT = https://ma3ut.standardchartered.co.kr/mpms_RESOURCE/hp/file/ap/pd/
#PMS_IMG_ROOT = https://owwwsit.standardchartered.co.kr/hp/file/ap/pd/
CMS_INCLUDE_LOANIMG_ROOT = https://owwwsit.standardchartered.co.kr/mb/loan/

#########################################
# 폰기프트 약관 URL
#########################################
PONE_GIFT_SERVICE_AGREE  = https://dev.pongift.com/api/etc/terms/33
PONE_GIFT_PROCESS_AGREE = https://dev.pongift.com/api/etc/terms/31
##이하 운영
#PONE_GIFT_SERVICE_AGREE  = https://pongift.com/api/etc/terms/16
#PONE_GIFT_PROCESS_AGREE = https://pongift.com/api/etc/terms/17

#########################################
# 키보드뱅킹 AES 암호화 대칭키 정의
#########################################
PAYKEY_SYMMETRIC_KEY=SCBankKeyBankKey


#########################################
# PUSH FCM URL
#########################################
PUSH_FCM_URL=https://194.168.1.11:1521/sms

########################################
# EDMI 전문 템플릿
########################################
EDMI_XML_TEMP_URL = /APP/mobile_SIT/ROOT.war/WEB-INF/repository/messenger/

########################################
#CI 관련
########################################
CI_SERVER_IP = 127.0.0.1
CI_SERVER_PORT = 8080

#######################################
# EDOC XVARM INFO
#######################################
EDOC_XVARM_HOST=10.61.17.198|10.61.13.87
EDOC_XVARM_HOST_01=10.61.17.198
EDOC_XVARM_HOST_02=10.61.13.87
EDOC_XVARM_PORT=2102
EDOC_XVARM_ID=SUPER
EDOC_XVARM_SECRET=SUPER

#######################################
# 3rd Party 모듈에서 장애발생시 운영 담당자에게 SMS를 보내기위한 담당자 핸드폰번호 정의
# XVARM , TSA
# (전화번호|전화번호|전화번호| 형태로 정의를하고 소스에서 파이프로 잘라서 사용한다.)
#######################################
EMERGENCY_REAL_MANAGER_HP=01090857350|01090857350|01090857350
EMERGENCY_REAL_MANAGER_HP_SEND_LIMIT_COUNT=1

#######################################
# IPINSIDE 관련 로그인 시 로직 SKIP 여부 (Y:Skip)
# PARSE_IPINSIDE_SKIP - FDS DB 관련
# PC_DIGNATE_SKIP - Auth Server 관련
# PC_FIX_SKIP - IPINSIDE DB 관련
#######################################
PARSE_IPINSIDE_SKIP=N
PC_DIGNATE_SKIP=N
PC_FIX_SKIP=N

#######################################
# 금융인증서 관련 PROPERTY 관리
# FINCERT_ORG_CODE - 이용기관 023
# FINCERT_API_KEY  - INIT시 필요한 APIKEY
# FINCERT_CLIENT_ORIGIN - Native Package Name
# FINCERT_CLIENT_CSS_URL_ARRAY - Custom CSS 적용 URL
# FINCERT_SDK_JS_URL - 금융결제원 Client SDK LOAD URL
#######################################
FINCERT_ORG_CODE=DB00230000
#FINCERT_ORG_CODE=D200900005
FINCERT_API_KEY=ad61d665-46ec-4e5d-9a9f-9ef272ca25ed
FINCERT_CLIENT_ORIGIN=com.scbank.ma30
FINCERT_CLIENT_CSS_URL_ARRAY=/resource/css/sdk.css|/resource/css/iphonx.css|/resource/css/s10.css|/resource/css/commonui.css
FINCERT_SDK_JS_URL=https://t-4user.yeskey.or.kr/v1/fincert.js
#FINCERT_SDK_JS_URL=https://fidoweb.yessign.or.kr:3300/fincert/v1/fincert.js
FINTECH_MA30_DOMAIN=https://ma3sit.standardchartered.co.kr

#MCI 로그 적재 활성화 여부(Y/N)
IS_ACTIVE_MCI_LOG=Y
#EDMI 로그 적재 활성화 여부(Y/N)
IS_ACTIVE_EDMI_LOG=Y
#######################################
# 전자등기 2024.09.30
#######################################
EREG_XVARM_HOST = 10.61.117.206
EREG_XVARM_PORT = 2102
EREG_XVARM_CLIP_URL = http://10.61.117.206:9010

#######################################
#VFDS 와 FDS 병행에 따른 변수 설정
#######################################
FDS_SW_YN=Y
VFDS_SW_YN=Y

#######################################
#Dfinder(REST API) 신규 추가로 인한 설정
#######################################
DFINDER_SERVER_URL = https://10.61.17.81:18443
DFINDER_SERVER_PRODUCE = /produce
DFINDER_SERVER_CONCURRENT = /concurrent
DFINDER_SERVER_RETRIEVE = /retrieve

#######################################
#기기지정 테이블 postgreSQL이관으로 인한 설정
#######################################
DEVICE_AUTH_SW = Y

#######################################
# 모바일 웹인 경우
#######################################
WEB_IPINSIDE_URL = http://10.61.17.220:20000

#######################################
# VFDS TIME_OUT 설정
#######################################
VFDS_TIME_OUT = 3000

#######################################
# 악성앱수집 호출 방법 선택(MESSAGE HUB : Y, RESTAPI : N)
#######################################
MALWARE_MESSAGE_YN = Y