#onlyone 서버 API 통신 IP
#onlyone.api.url=https://10.61.222.42:10544
#onlyone.api.url=https://10.61.222.42:10543
onlyone.api.url=https://krcalabp31:10544

#onlyone 서버 API 통신 baseURL
onlyone.api.baseurl=https://scbapi.sellerbot.co.kr

#onlyone 서버 API 통신 svc_id
onlyone.api.svc_id=scbank


#onlyone 서버 API 통신 svc_cert_key
onlyone.api.svc_cert_key=a935182d-e19d-4be9-8b60-402f09ec38a0

#onlyone 고객 가입여부 API
onlyone.api.CUSTOMER_YN.url = /onlyone/v1/alliance/cust/confirm
onlyone.api.CUSTOMER_YN.method = POST
onlyone.api.CUSTOMER_YN.host=scbapi.sellerbot.co.kr

#onlyone 상담 데이터 API
onlyone.api.CONSULT_DATA.url = /onlyone/v1/alliance/cust/consult
onlyone.api.CONSULT_DATA.method = POST
onlyone.api.CONSULT_DATA.host=scbapi.sellerbot.co.kr

#onlyone 건별 대출 데이터 API
onlyone.api.LOAN_DATA.url = /onlyone/v1/alliance/cust/loan/screening
onlyone.api.LOAN_DATA.method = POST
onlyone.api.LOAN_DATA.host=scbapi.sellerbot.co.kr

#onlyone 사후관리 등록해지 데이터 API
onlyone.api.LOAN_MANAGE.url = /onlyone/v1/alliance/cust/loan/manage/req
onlyone.api.LOAN_MANAGE.method = POST
onlyone.api.LOAN_MANAGE.host=scbapi.sellerbot.co.kr

#onlyone 사후관리 정산 데이터 API
onlyone.api.LOAN_CALCULATE.url = /onlyone/v1/alliance/cust/loan/manage
onlyone.api.LOAN_CALCULATE.method = POST
onlyone.api.LOAN_CALCULATE.host=scbapi.sellerbot.co.kr

#onlyone 시스템 관리 API
onlyone.api.SYSTEM_MANAGE.url = /onlyone/v1/alliance/system/checking
onlyone.api.SYSTEM_MANAGE.method = POST
onlyone.api.SYSTEM_MANAGE.host=scbapi.sellerbot.co.kr
