# WFX 환율조회 타임아웃 (초 단위)
wfx.transper.rate.timeout=60

# 고객 적용환율 및 우대율 ( % )
wfx.transper.spreadrate=0.95
wfx.transper.preferentialrate=60

#WFX API 설정값
wfx.api.baseurl = https://apiinttest.standardcharteredad.co.kr:9443
wfx.api.TOKEN_DATA.url = /wealthfx/oauth2/token
wfx.api.TOKEN_DATA.method = POST
wfx.api.region = kr
wfx.api.xJwtAssertion = bl4c-kp1n-k1ny-0ur4-r34b-00b5
wfx.api.clientId = WFX
wfx.api.clientSecret = WFX

#SPOT_RATE
wfx.api.SPOT_RATE.url = /wealthfx/v3/rates/spot-rate?currency=
wfx.api.SPOT_RATE.method = GET

#QUOTE
wfx.api.QUOTE.url = /wealthfx/v3/gworders/quote
wfx.api.QUOTE.method = POST

#ORDERS
wfx.api.ORDER.url = /wealthfx/v3/gworders/order
wfx.api.ORDER.method = POST

# WFX 대미환산금액 최소/최대금액 (달러 기준) //week : 평일 09:00 - 16:30 , holi  평일 16:30 - 익일 08:59 && 휴일 및 공휴일
wfx.transper.convert.weekMinAmount	= 10
wfx.transper.convert.weekMaxAmount	= 300000
wfx.transper.convert.holiMinAmount	= 10
wfx.transper.convert.holiMaxAmount	= 10000

# 평일 적용시작시간
wfx.transper.startApplTime	= 0900
# 평일 적용종료시간
wfx.transper.endApplTime	= 1630

#######################################
# WFX API 통신 장애발생시 운영 담당자에게 SMS를 보내기위한 담당자 핸드폰번호 정의
# (전화번호|전화번호|전화번호| 형태로 정의를하고 소스에서 파이프로 잘라서 사용한다.)
#######################################
wfx.emergency.manager.hp = 01053836768|01035895842|01029103631|01099058368|01044221311|01091464816|01052160960|01040773187|01042488424|01029056762|01024208707|01022937549|01093349313|01050180769
