# mock 세션 기능 활성화 여부
mock.session.enabled = false

# 로그인 활성화 여부
mock.session.login.enabled = false

# 로그인ID
mock.session.login.userId = OPTE789

# 로그인 세션
mock.session.loginSession.ConnectType = 2
mock.session.loginSession.UserID = OPTE789
mock.session.loginSession.YOLRSOTGB = OPTE789   
mock.session.loginSession.PerNoPart = 1
mock.session.loginSession.PerBusNo = 7001011456789
mock.session.loginSession.SSRBrNo = 1
mock.session.loginSession.UserCmfNo = 1
mock.session.loginSession.UserCifNo = 1

mock.session.loginSession.CustGubun = 1
mock.session.loginSession.UseGrade = 1
mock.session.loginSession.RegiBranchNum = 1
mock.session.loginSession.EngCustName = 1
mock.session.loginSession.CustName = \uC5C5\uBB34\uD14C\uC2A4\uD2B8

mock.session.loginSession.AllAccountListYN = 1
mock.session.loginSession.ReferAcctInBoxYN = 1
mock.session.loginSession.DrawAcctInBoxYN = 1
mock.session.loginSession.VirtualAccountYN = 1
mock.session.loginSession.UsingFamilyCardYN = 1
mock.session.loginSession.HDCardYN = N
mock.session.loginSession.BCCardYN = N

mock.session.loginSession.IssueID = 1
#//1:가입, 4:정지, 8:해지
mock.session.loginSession.YOSMTGB = 1

mock.session.loginSession.SafeCardKind = 1
mock.session.loginSession.SafeCardState = 1
mock.session.loginSession.SafeCardINDEX = 000005
mock.session.loginSession.SafeCardINDEX2 = 000020
mock.session.loginSession.SafeCardIssueNum = 00047010
mock.session.loginSession.SafeCardBranchNum = 1
mock.session.loginSession.PCLoanPromiseYN = 1
mock.session.loginSession.OtherBankErrorYN = 1

mock.session.loginSession.TeleOne = 1
mock.session.loginSession.TeleTwo = 1
mock.session.loginSession.TeleThree = 1
mock.session.loginSession.HPOne = 02
mock.session.loginSession.HPTwo = 3433
mock.session.loginSession.HPThree = 2839
mock.session.loginSession.HpNum = 02-3433-2839

# MOTP 로그인시
#mock.session.loginSession.YISCBUNH = 1
#mock.session.loginSession.YIFIDO = G 

mock.session.loginSession.TransDate = 1
mock.session.loginSession.TransTime = 1
mock.session.loginSession.LoginDateTime = 1

mock.session.loginSession.IsForienType = N
mock.session.loginSession.AuthType = IB

mock.session.loginSession.IPProtectYN = N
mock.session.loginSession.IPBlockYN = 1
mock.session.loginSession.FlagIsAbroadYN = 1

mock.session.loginSession.YOPCGB = 1
mock.session.loginSession.OtherPCYes = N
mock.session.loginSession.PcFixValue = 0

mock.session.loginSession.FinalUseDate = 1   
mock.session.loginSession.FinalUseTime = 1   
mock.session.loginSession.FinalNetwork = 1   
mock.session.loginSession.FinalServiceCode = 1   
mock.session.loginSession.LastTransDate = 1   
mock.session.loginSession.AtonceApprState = 1   
mock.session.loginSession.AtonceAdminNumState = 1   
mock.session.loginSession.AtonceTransState = 1   
mock.session.loginSession.ForcurReferState = 1   
mock.session.loginSession.LoanReferState = 1   
mock.session.loginSession.TotAcctPrintYN = 1   
mock.session.loginSession.RemitType = 1   

## 외환
mock.session.loginSession.YOPASSYN = 1
mock.session.loginSession.YOGEOJU = 1
mock.session.loginSession.YOKWASE = 1
mock.session.loginSession.YOSMBH = 1

mock.session.loginSession.YOGEORE = 1   
mock.session.loginSession.YOSIMPLE = 1   

#프리미엄뱅킹 등급
mock.session.loginSession.YOPBANK = 1   
mock.session.loginSession.YOJDNAME = 1   
mock.session.loginSession.YOJDOPNO = 1   
mock.session.loginSession.YOGBRNM = 1   
mock.session.loginSession.YOJDTEL = 1   
mock.session.loginSession.YOPNTJAN = 1   



# 글로벌 세션
mock.session.globalSession.VFDSDeviceKey = 

mock.session.globalSession.UserID = test01
mock.session.globalSession.YOLRSOTGB = test01

mock.session.globalSession.HDCardYN = N
mock.session.globalSession.BCCardYN = N

mock.session.globalSession.LoginUserID = 2
mock.session.globalSession.e_UserID = 2
mock.session.globalSession.e_ConnectType = 2
mock.session.globalSession.deviceCertExistYn = 2
mock.session.globalSession.finCertExistYn = 2
mock.session.globalSession.USER_CI_INFO = 2

