########################################
# 업무 프라퍼티 설정 영역
########################################

#이중 로그인체크 허용여부 Y:허용, N:불가
ALLOW_DUPLICATE_LOGIN = Y

########################################
#BCP 관련 프로퍼티
#10.61.17.101	개발
#211.32.160.65	BCP IP변경
#10.61.11.150	운영
########################################
BCPDecryptService_ip=10.61.17.101
BCPDecryptService_port=20005
BCPDecryptService_characterSet=EUC-KR
BCPDecryptService_timeout=300000

########################################
#[2018.12.06] bill SMTP 정보
########################################
SMTP_OUTLOOK_USE = Y
SMTP_OUTLOOK_IP = 10.61.20.22
SMTP_OUTLOOK_PORT = 25 
SMTP_OUTLOOK_SENDER = BB119Helpdesk
SMTP_OUTLOOK_DOMAIN = @scfirstbank.com

#SCNF사용 SIT/UAT : N, REAL:Y
IS_REAL = N

HOMEBRANCH = 0019

AGENTBRANCH = 0019

SUBTASKCODE = 0001

########################################
# Syncat 서비스
########################################
SYNCAT_GW_IP = 211.32.160.69
SYNCAT_GW_PORT = 20000

########################################
# SMS 서비스
########################################
sms.server.ip = 194.168.1.27
sms.server.port = 9090
lms.server.port = 9192

########################################
# PKI모듈 관련
########################################
PKI_TIME_URL = /bsoi/commons/nonceTime?action=time
PKI_COPY_URL = /bsoi/commons/certRelay
VPCG_AGENT_URL = /bsoi/commons/vpcgAgent
VPCG_APP_URL = /resource/product/wizvera/delfino/delfinoApp.html
CRT_TermGijun = M
CRT_TermPeriod = 1
CRT_fincertTermPeriod = 3
CRT_kfbTermPeriod = 30
CRT_YESSIGN_CAIP = 203.233.91.231
CRT_YESSIGN_CAPORT = 4512
CRT_RegiBranchNum = 860
#CRT_yesDN1=CN=yessignCA-Test Class 2, OU=AccreditedCA, O=yessign, C=kr
#CRT_yesDN2=CN=yessignCA-Test Class 3, OU=AccreditedCA, O=yessign, C=kr
#CRT_yesDN3=CN=yessignCA-TEST, OU=AccreditedCA, O=yessign, C=kr
#CRT_yesDN4=CN=yessignCA-Test Class 4, OU=AccreditedCA, O=yessign, C=kr
CRT_CertConfigPath = /APP/product/initech/mobile_ut/iniplugin/properties/CertConfig.properties
CRT_SG_REG_IB_RANCH_NUM = 860
CRT_SG_POLICYID_P = 1 등급 인증서(개인)
CRT_SG_POLICYID_C = 1 등급 인증서(법인)
#CRT_RaServer = 23.220.24.80
CRT_RaServer = 10.61.157.141
INITECH_PROPERTIES_JCERTOID_PATH = /APP/product/initech/mobile_ut/iniplugin/properties/jCERTOID.properties
INITECH_PROPERTIES_INISAFESIGN_PATH = /APP/product/initech/mobile_ut/iniplugin/properties/INISAFESign.properties
INITECH_PROPERTIES_OCSPGD_PATH = /APP/product/initech/mobile_ut/iniplugin/properties/jOCSPGD.properties
INITECH_PROPERTIES_OPPRA_PATH = /APP/product/initech/mobile_ut/iniplugin/properties/jOPPRA.properties
INITECH_CA_FILTER=Test

########################################
# 전자서명 설정
########################################
SDTA_TYPE = D
SYS_NAME = MA30
SIGN_DIR = /signdata/stores
SIGN_DIR_BACKUP = /signdata/stores/backup
INITECH_INISAFENET_PATH=/APP/product/initech/mobile_ut/inisafenet/properties/INISAFENet.properties

########################################
#인증서가져오기/내보내기
########################################
GET_CERT_THIS_SERVER_INDEX = 0
GET_CERT_SERVER_URL1 = https://ma3ut.standardchartered.co.kr/product/pki/GetCertificate_v12.jsp
GET_CERT_SERVER_URL1 = https://ma3ut.standardchartered.co.kr/product/pki/GetCertificate_v12.jsp
GET_CERT_SERVER_URL1 = https://ma3ut.standardchartered.co.kr/product/pki/GetCertificate_v12.jsp

########################################
# 스마트오퍼
########################################
sobroker.recommendURL = http://10.61.157.133:9010/so-web-app/so/recommend
sobroker.timeout = 1000

########################################
# 실명인증
########################################
NAMECHECK_IP = 211.32.160.69
NAMECHECK_PORT = 19000
CARD_24365_TIME = 800
#SIT , UAT는 Y , REAL은 N ( 테스트계 실명인증은 무조건 ByPassFlag
TESTNAMECHKFLAG = Y

########################################
# 블록체인(뱅크사인)
########################################
BCNS_URL = http://10.61.17.184:8980
KFB_SIGN_VERIFY_LIC_PATH=/APP/product/kfbsign/jcaos.lic

########################################
# 메일서버
# 변경전(23.20.12.171) -> 변경후(10.61.17.236)
########################################
IMAS_IP = 10.61.17.236
IMAS_PORT = 9100

########################################
# CONGNAMUL(영업점찾기)
########################################
CONGNAMUL_IP = 211.32.160.69
CONGNAMUL_PORT = 18000

########################################

########################################
# 바로상담 10.61.11.181(변경전) -> 10.61.13.204(변경후)
########################################
ip value = 10.61.11.181 
port value = 10010
########################################

# nfilter BCP 위치는 나중에 수정 필요함.
########################################
#NFILTER_PROPERTIES_PATH=/smbank/SMBank_app.ear/SMBankWeb.war/WEB-INF/nfilter.properties 
NFILTER_PROPERTIES_PATH =C:/scbank/workspace/scbank-ma30-webapp/src/main/webapp/WEB-INF/product/nshc/config/nfilter-local.properties

########################################
# 전자문서관련 (Clip,mp 등)
########################################
CLIP_REPORT_URL=https://clipsit.standardchartered.co.kr/clip/
EDOC_SELFBANK_REPO=/scnf/tscnf_sit.ear/obibWeb.war/WEB-INF/clipreport4/pdf/
EDOC_SELFBANK_REPO_WAS=C:/scbank/workspace/scbank-ma30-webapp/src/main/webapp/edoc/loan/clipreport4/pdf/
FILE_SYNC_PROPERTIES_PATH=/APP/mobile_UT/ROOT.war/WEB-INF/classes/cfg/properties/FilesyncClient.properties
BANCA_HTML_PATH=/APP/mobile_UT/ROOT.war/edoc/banca/
BANCA_HTML_URL=https://ma3ut.standardchartered.co.kr/edoc/banca/

#서버 IP
SIGN_WAS_IP=10.61.17.91

#전자문서 중계서버
EDOC_RELAY_SERVER_URL=http://10.61.17.198:8580
EDOC_RELAY_SERVER_URL_2=http://10.61.17.198:8580
EDOC_RELAY_SERVER_URL_3=http://10.61.17.198:8580

#KTNET
KTNET_PROP_ROOT=/APP/product/ktnet
KTNET_PROP_PATH=/APP/product/ktnet/config/tradesign3280.properties
KTNET_CERT_PATH=/APP/product/ktnet/config/ServerCert/signCert.der
KTNET_PRIV_PATH=/APP/product/ktnet/config/ServerCert/signPri.key
KTNET_PRIV_SECRET=asdfasdf

########################################
# Homepage URL	// REAL -> [www] 적용부탁드립니다.
########################################
HOMEPAGE_URL=https://owwwsit.standardchartered.co.kr


#MA30 URL 
MA30_URL=https://ma3ut.standardchartered.co.kr

#시스템 전환 시간.
S_CK_TIME=2355,0020
#페이지체크 무시 URI (구분자는 |)
#PAGECHECK_IGNORE_URI_LIST=/common/MA3CMMINF001_100S.act|/common/MA3CMMERR001.mnu|/common/MA3CMMINF003_100S.act|/custcenter/MA3CSTSTI004.mnu
PAGECHECK_IGNORE_URI_LIST =/process/api/v1/common/functions/authority/checkMenuInfo|/process/api/v1/common/functions/holiday/list|/process/api/v1/common/settings/app/getInitInfo|/process/api/v1/common/settings/code/list|/process/api/v1/customer/info/login/inquirySessionInfo
#페이지체크 무시 메뉴ID (구분자는 |)
PAGECHECK_IGNORE_MENU_ID = COMCMP004_01MS|COMCMP004_02MS|COMCMP004_03MS|SVCSUP003|MA3CSTSTI004|COMETC000

#default사용자정보
DEFAULT_BRANCHNO=860

#Raon Service Info
RAON_ADAPTER_IP=10.61.17.198
RAON_ADAPTER_PORT=7035
RAON_ADAPTER_TIMEOUT=10000
RAON_CUST_ID=9999E17A6143115164A5
RAON_SERVICE_ID=161F3A85927B32A50810

#실명인증
KOREA_TRUST_WORKTYPE=checkKoreaTrustCheck
KOREA_TRUST_ADD_KEY=80421577

########################################
#ClickToCall Info
########################################
clickToCall.server.ip=10.61.13.204
clickToCall.server.port=10010


########################################
#SSO
########################################
SSO_SERVER_URL=http://pkisso.standardchartered.co.kr:6480

#########################################
# 펀드 PDF
#########################################
PMS_FILE_ROOT=/APP/mpms_UT/ROOT.war

#########################################
# FIDO(RAON, ONEPASS)
#########################################
FIDO_SERVER_DOMAIN=http://10.61.17.91:8890/interfBiz/processRequest.do
FIDO_SERVER_TIMEOUT=10000
FIDO_SITE_ID=SIT01SCBANK000000000
FIDO_SVC_ID=SVC01SCBANK000000000


#########################################
# PMS 이미지 경로
#########################################
PMS_RESOURCE_ROOT = https://ma3ut.standardchartered.co.kr/mpms_RESOURCE
PMS_IMG_ROOT = https://ma3ut.standardchartered.co.kr/mpms_RESOURCE/hp/file/ap/pd/
#PMS_IMG_ROOT = https://owwwsit.standardchartered.co.kr/hp/file/ap/pd/

#########################################
# 키보드뱅킹 AES 암호화 대칭키 정의
#########################################
PAYKEY_SYMMETRIC_KEY=SCBankKeyBankKey


#########################################
# PUSH FCM URL
#########################################
PUSH_FCM_URL=https://194.168.1.11:1521/sms

########################################
#CI 관련
########################################
CI_SERVER_IP = 127.0.0.1
CI_SERVER_PORT = 8080

########################################
#모바일현금카드 MCC
########################################
MCC_API_URL = https://thce.kftc.or.kr:4443/api/v1/auth
MCC_TRANCODE = https://thce.kftc.or.kr:4443/api/v1/pay/trancode
MCC_TRAN_RESULT = https://thce.kftc.or.kr:4443/api/v1/pay/result
MCC_MEMBER_URL = https://hce.kftc.or.kr/html/store.html
MCC_BANK_ID = sc
MCC_API_KEY = Ip9tllRLXwBPlfGg74dgPxWEt5YjE9FC9oPAXTJ7GNeM

#######################################
# 전자등기 2024.09.30
#######################################
EREG_XVARM_HOST = 10.61.117.206
EREG_XVARM_PORT = 2102
EREG_XVARM_CLIP_URL = http://10.61.117.206:9010

#MCI 로그 적재 활성화 여부(Y/N)
#IS_ACTIVE_MCI_LOG=Y
#EDMI 로그 적재 활성화 여부(Y/N)
#IS_ACTIVE_EDMI_LOG=Y
#######################################
# 전자등기 2024.09.30
#######################################
EREG_XVARM_HOST = 10.61.117.206
EREG_XVARM_PORT = 2102
EREG_XVARM_CLIP_URL = http://10.61.117.206:9010

#######################################
#VFDS 와 FDS 병행에 따른 변수 설정
#######################################
FDS_SW_YN=Y
VFDS_SW_YN=Y

#######################################
#Dfinder(REST API) 신규 추가로 인한 설정
#######################################
DFINDER_SERVER_URL = https://10.61.17.81:18443
DFINDER_SERVER_PRODUCE = /produce
DFINDER_SERVER_CONCURRENT = /concurrent
DFINDER_SERVER_RETRIEVE = /retrieve

####################################### 
#기기지정 테이블 postgreSQL이관으로 인한 설정
#######################################
DEVICE_AUTH_SW = Y

#######################################
# 모바일 웹인 경우
#######################################
WEB_IPINSIDE_URL = http://10.61.17.220:20000

#######################################
# VFDS TIME_OUT 설정
#######################################
VFDS_TIME_OUT = 3000

#######################################
# 악성앱수집 호출 방법 선택(MESSAGE HUB : Y, RESTAPI : N)
#######################################
MALWARE_MESSAGE_YN = Y