###########
# 화상상담 API 
###########

#화상상담 서버 API 통신 API baseURL
ras.api.url=https://apiinttest.standardcharteredad.co.kr:9443
#ras.api.url=https://apiinttest.standardcharteredad.co.kr:8443
#화상상담 서버 API 통신 API baseURL
ras.api.baseurl=https://apiinttest.standardcharteredad.co.kr:9443
#화상상담 서버 API 통신 svc_id
ras.api.svc_id=
#화상상담 서버 API 통신 svc_cert_key
ras.api.svc_cert_key=
#화상상담 연결 URL
ras_connect_url = https://ras-sit.standardchartered.co.kr


#화상상담 - 토큰발급 API
ras.api.TOKEN_DATA.url = /ras/oauth2/token
ras.api.TOKEN_DATA.method = POST
ras.api.TOKEN_DATA.host=

#화상상담 - 고객 정보 저장 API
ras.api.SAVE_CUST_INFO.url = /ras/sc/customer/
ras.api.SAVE_CUST_INFO.method = POST
ras.api.SAVE_CUST_INFO.host=

#화상상담 - 신분증 진위여부 저장 API
ras.api.SAVE_VERIFY_ID.url = /ras/sc/customer/verify
ras.api.SAVE_VERIFY_ID.method = POST
ras.api.SAVE_VERIFY_ID.host=

#화상상담 - 거래 데이터 조회 API
ras.api.INQ_VDO_TRAN.url = /ras/sc/customer/vdo-tran
ras.api.INQ_VDO_TRAN.method = GET

#화상상담 - 거래 고객 검증 API
ras.api.INQ_VDO_VALID.url = /ras/sc/customer/vdo-tran-valid
ras.api.INQ_VDO_VALID.method = POST
ras.api.INQ_VDO_VALID.host=

