# bizmarket 서버 API 통신 IP
bizmarket.api.url = https://10.61.223.126:10545/thankqpon

#bizmarket 서버 API 통신 baseURL
bizmarket.api.baseurl = https://10.61.223.126:10545/thankqpon

#bizmarket 서버 API 통신 svc_id
bizmarket.api.svc_id = 

#bizmarket 서버 통신 svc_cert_key
bizmarket.api.svc_cert_key = 

# bizmarket MMS발송 (쿠폰번호 추가) API
bizmarket.api.COUPON_SEND.url = /SendCouponGetPin.do
bizmarket.api.COUPON_SEND.method = POST

# bizmarket 거래번호 조회 (SSO) API
bizmarket.api.GET_TRADE_NO.url = /getTradeno.do
bizmarket.api.GET_TRADE_NO.method = POST