#방카 지점번호
BANCA_WIBRANCHCODE = 024
#방카 사용자아이디
BANCA_WIUSERID = 999992
#FILE_SYNC_PROPERTIES_PATH = /APP/mobile_UAT/ROOT.war/WEB-INF/classes/cfg/site/MA3/properties/app

#중소기업분할상환대출 OUTLOOK 메일전송
SMTP_OUTLOOK_USE = Y
SMTP_OUTLOOK_IP = 10.61.20.22
SMTP_OUTLOOK_PORT = 25
SMTP_OUTLOOK_SENDER = BB119Helpdesk
SMTP_OUTLOOK_DOMAIN = @scfirstbank.com

#이미지 파일 Upload경로(UAT)
NON_FACE_IMAGE_PATH = /APP/mobile_UAT/ROOT.war/nonFaceIDCard/

#테스트 서버 용
NON_FACE_IMAGE_PATH_MPP = /SCNF/SCNF/ROOT.war/NONFACE

#안면인식 이미지 파일 Upload경로
FACE_ID_IMAGE_PATH = /APP/mobile_UAT/ROOT.war/faceId/

#테스트 서버 용
MPP_BBCA_IMG_PATH = /SCNF/attachments
  
#SCP ShellScript 경로(SIT)
MPP_SCP_PATH_SM = /APP/mobile_UAT/ROOT.war/WEB-INF/execs

#MP 테스트 1서버 SCP 전송여부 확인
MPP_CHECK_SCP_PATH1 = http://10.61.17.126:11780/webservices/proworks/execute
#MP 테스트 2서버 SCP 전송여부 확인
MPP_CHECK_SCP_PATH2 = http://10.61.17.126:11780/webservices/proworks/execute

#OCR 서버 (개발)
OCR_DECIPHER_DEV_IP = http://10.61.17.198:8012
#OCR 서버 (운영)
OCR_DECIPHER_REAL_IP = http://10.61.13.86:8012
#OCR 서버 (운영2)
OCR_DECIPHER_REAL_IP_2 = http://10.61.13.87:8012

#SCP SIT HOME 경로
SCNF_HOME_PATH_DEV = /APP/product/KoreaID/
#SCP REAL HOME 경로
SCNF_HOME_PATH_REAL = /APP/product/KoreaID/

#PMS 파일(PDF) 경로
PMS_FILE_PDF_PATH = /mpms_RESOURCE/hp/file/ap/pf/

#MACADDR 더미
MAC_ADDR_DUMMY_VALUE = 02:00:00:00:00:00

#######################################################
#모바일현금카드 MCC 2023.09.06
# MCC_PROXY_YN		: 통신구분 (Y:Proxy 통신 / N:Native 통신)
# MCC_BANK_ID		: 은행별 ID (sc)
# MCC_ORG_CODE		: 은행코드 (023)
# MCC_API_PATH		: API Key의 경로
# MCC_API_PASS		: API Password
# MCC_API_KEY		: API Key
# MCC_API_URL_NATIVE: 공통 URL (Native통신)
# MCC_API_URL_PROXY	: 공통 URL (Proxy통신
# MCC_AUTH			: API 인증
# MCC_TRANCODE		: 인증번호 생성
# MCC_TRAN_RESULT	: 거래결과 조회
# MCC_QR_VERIFY		: QR코드 거래일련번호 검증 요청
# MCC_MEMBER_URL	: 가맹점 안내
#######################################################
MCC_PROXY_YN = N
MCC_BANK_ID = sc
MCC_ORG_CODE = 023
MCC_API_PATH = /APP/mobile/ROOT.war/WEB-INF/classes/cfg/properties/master.key
MCC_API_PASS = 20200115
MCC_API_KEY = Ip9tllRLXwBPlfGg74dgPxWEt5YjE9FC9oPAXTJ7GNeM
MCC_API_URL_NATIVE = https://thce.kftc.or.kr:4443
MCC_API_URL_PROXY = https://thce.kftc.or.kr:4443
MCC_AUTH = /api/v1/auth
MCC_TRANCODE = /api/v1/pay/trancode
MCC_TRAN_RESULT = /api/v1/pay/result
MCC_QR_VERIFY = /api/v1/qr/verify
MCC_MEMBER_URL = https://hce.kftc.or.kr/html/store.html

#IB URL
IB_URL=https://oibuat.standardchartered.co.kr

#키보드뱅킹> 오픈뱅킹 이체한도
PAYKEY_OBS_TRAN_LIMIT = 1000000

#키보드뱅킹 로그 YN
PAYKEY_LOG_YN = Y

#######################################
# 에어브릿지 WEB-SDK 초기화 정보
# 개발 : scma30dev / 6be440071e1b4ccda696efdcdf7f1b4f
# 운영 : scbmobile / 94b739bcf9e14947ae47538eb94471f3
#######################################
AIRBRIDGE_APP=scma30dev
AIRBRIDGE_WEB_TOKEN=6be440071e1b4ccda696efdcdf7f1b4f

#######################################################
# 금융인증서 추가로 인한 RA 조회시 필요한 파라미터 정의
# 파라미터순서 : CUSTGUBUN(1,2) | RAGUBUN(1,2,6) | CERTPOLICY(01,04,16)
#######################################################
#개인 금융 인증서
RA_USER_SEARCH_PERSONAL_FINCERT = 1|6|16
#개인 공동 범용인증서
RA_USER_SEARCH_PERSONAL_UNIVERSAL = 1|2|01
#개인 공동 인증서
RA_USER_SEARCH_PERSONAL_COMMON = 1|1|04

#통합대출상담 건강보험료율
#2023.01.16 건보율 변경 (3.495 > 3.545)
NATIONAL_HEALTH_INSURANCE_RATE=3.545

#######################################################
# 약관 및 상품설명서 PDF 다운로드 정의
#######################################################
#신용대출 통합상담
HOMEPAGE_CREDIT_LOAN_AGREE_PDF   = https://owwwsit.standardchartered.co.kr/mb/pe?prc=128&sch=1
HOMEPAGE_CREDIT_LOAN_PRODUCT_PDF = https://owwwsit.standardchartered.co.kr/mb/pe?prc=128&sch=4
#주택담보대출
HOMEPAGE_MORTGAGE_LOAN_AGREE_PDF   = https://owwwsit.standardchartered.co.kr/mb/pe?prc=3005&sch=1
HOMEPAGE_MORTGAGE_LOAN_PRODUCT_PDF = https://owwwsit.standardchartered.co.kr/mb/pe?prc=3005&sch=4
#전세대출
HOMEPAGE_WARRANT_LOAN_AGREE_PDF   = https://owwwsit.standardchartered.co.kr/mb/pe?prc=132&sch=1
HOMEPAGE_WARRANT_LOAN_PRODUCT_PDF = https://owwwsit.standardchartered.co.kr/mb/pe?prc=132&sch=4
#기업대출
HOMEPAGE_COMPANY_LOAN_AGREE_PDF   = https://owwwsit.standardchartered.co.kr/mb/pe?prc=5206&sch=1
HOMEPAGE_COMPANY_LOAN_PRODUCT_PDF = https://owwwsit.standardchartered.co.kr/mb/pe?prc=5206&sch=4
#약관 및 상품설명서 공통 URL
HOMEPAGE_AGREE_PDF   = https://owwwsit.standardchartered.co.kr/mb/pe?sch=1&prc=
HOMEPAGE_PRODUCT_PDF = https://owwwsit.standardchartered.co.kr/mb/pe?sch=4&prc=
#약관 및 상품설명서 공통 URL(위에 Key 사용하지않을예정)
HOMEPAGE_PDF_URL = https://owwwsit.standardchartered.co.kr/hp/file/ap/pd/

#ObsCryptoUtils 하드코딩된 IV,KEY 프로퍼티로관리하도록변경
#이행 시 삭제가 필요한 경우 ObsCryptoUtils도 변경필요
OBSCRYPTOUTIL_IV  = D74CD6D90A7F7BCB3536AB80DE20C614
OBSCRYPTOUTIL_KEY = 461CB533CC0195DA39928063A138CBCB

#######################################
# 푸망 초기화 정보
# 개발 : scma30dev / HLWOa5Y5tIe5T2OfFywlFAFuc5E0wdQtVtQqZtSl / x91Xu5yBtD9tv0x4dHC7HyoOBZIRLf4BB8N8wgPQ
# 운영 : scbmobile / HLWOa5Y5tIe5T2OfFywlFAFuc5E0wdQtVtQqZtSl / rZuLPQXgEqrcPfbCd0H70u0qT9nsOTKIYmbuNTR9
POOMANG_ADMIN_TOKEN=HLWOa5Y5tIe5T2OfFywlFAFuc5E0wdQtVtQqZtSl
POOMANG_PLAYER_TOKEN=x91Xu5yBtD9tv0x4dHC7HyoOBZIRLf4BB8N8wgPQ


######################################
# 입출금 비교대상 상품명
######################################
SALES_CASA_PRODUCT_NM = 제일EZ|내월급|마이100|내지갑|마이시그니처|마이줌|마이심플|두드림|두드림2U|Hi|모아예금


#RAON FIDO Admin 관리자 페이지 계정ID
FIDO_ADMIN_ID=onepassadmin

#디지털인증서 로그인 Verify(Y-활성화/N-비활성화)
IS_DISTCERT_VERIFY=Y
#디지털인증서 LOG Tracking(Y-활성화/N-비활성화)
IS_DISTCERT_LOGTRKING=Y
#디지털인증서 발급 1단말체크(Y-활성화/N-비활성화)
IS_DISTCERT_ONEDEVICE=Y

########################################
# 네이버 API
# X-NAVER-CLIENT-ID				- 클라이언트 아이디
# X-NAVER-CLIENT-SECRET		- 클라이언트 시크릿
# NAVER_OPENAPI_URL				- https://openapi.naver.com
# NAVER_ROMANIZATION_URL	- 한글인명-로마자 변환 URL
########################################
NAVER_OPENAPI_URL = https://naveropenapi.apigw.ntruss.com:6003
NAVER_ROMANIZATION_URL = /krdict/v1/romanization
X-NAVER-CLIENT-ID = ej6bn02eec
X-NAVER-CLIENT-SECRET = zS28pgBWdDBPQRR4lc1PSgibGdFCzyO1blAGOJUb

########################################
# 공공데이터포털 휴폐업 상태 조회 API
# ODCLOUD_OPENAPI_KEY 		- 클라이언트 KEY (LIH - 운영API 영향주지 않도록 개발환경은 별도 사용)  
# ODCLOUD_OPENAPI_URL 		- https://api.odcloud.kr
# ODCLOUD_OPENAPI_TAXSTATUS - 사업자 상태조회 URL
########################################
ODCLOUD_OPENAPI_KEY = RPKsihr6ayQS%2FJmu9gkKQNhgFCiFnMsfAY%2Fu1jaa6wSm6CiMwrZscb2hKnLwZkQH01hJkU38bmqftfl2T%2FMKpw%3D%3D
ODCLOUD_OPENAPI_URL = https://api.odcloud.kr:6002
ODCLOUD_OPENAPI_TAXSTATUS = /api/nts-businessman/v1/status?serviceKey=

########################################
# CDD유효기간도래 기간설정 (해당날짜 미만으로 관리)
CDD_EFFECTIVE_DATE = 90
########################################

########################################
# [2023.06.22 CDD자동화] KAIS(KCDD) 처리상태조회 폴링 설정.
# KCDD_POLLING_YN = 자동화실행여부(Y:자동화, N:수동, default : 'N')
# KCDD_POLLING_SECONDS = 요청시간(초단위)
# KCDD_POLLING_COUNT = 횟수.
# ex. 10초에 한번씩 5번 폴링. 
########################################
KCDD_POLLING_YN = Y
KCDD_POLLING_SECONDS = 5
KCDD_POLLING_COUNT = 10

#######################################################
# [2023.06.22 CDD자동화] EDMI to KAIS Header Info
# EDMI_CAPTURE_TARGET_SYSTEM_ERROR_SKIP = 응답 에러 체크 로직 제외 처리.
#    -  EDMI 응답값 'RANDATA/YOPBGTB/YOGHERR'
#    -  추가 할 내용은 '|'문자 뒤에 추가 할 것!
#######################################################
EDMI_CAPTURE_TARGET_SYSTEM_ERROR_SKIP = KAIS|
EDMI_CAPTURE_TARGET_SYSTEM_KAIS = KAIS
EDMI_NS_TYPENAME_KAIS	      = Risk:mbcommonroute
EDMI_NS_MSGSENDERBODY_KAIS	  = MB
EDMI_NS_SENDERDOMAINBODY_KAIS = Risk

#######################################################
# [2024.07.21 전자등기] EReg Header Info
#######################################################
EDMI_CAPTURE_TARGET_SYSTEM_EReg = EReg
EDMI_NS_TYPENAME_EReg	      = GroupFunctions:mobileBCommonRoute
EDMI_NS_MSGSENDERBODY_EReg	  = MB
EDMI_NS_SENDERDOMAINBODY_EReg = GroupFunctions

########################################
#HSM WorkingKey 프로퍼티 위치
########################################
HSM_WORKING_KEY_FILE = /APP/product/itls/work/workingKey.properties
HSM_NOT_USE_PROPERTY_PATH = /APP/product/itls/work/TempWorkingKey.properties

#이체 입금계좌 자동완성 기능(Y-활성화 /N-비활성화, CHECK-개수)
TRN_DRAWACCT_AUTO_FUNCTION_YN = Y
TRN_DRAWACCT_AUTO_FUNCTION_CHECK = 1

#전체 메뉴화면 최근 사용메뉴 전시기능 제공(Y-활성화 /N-비활성화, COUNT-개수)
MOR_LATELY_USE_DISPLAY_YN = Y
MOR_LATELY_USE_DISPLAY_COUNT = 4

########################################
#2023.12.15 금융소비자보호법 2차 계약서 임시 경로
########################################
CONTRACT_DOC_TEMP_PATH = /APP/mpms_RESOURCE/TEMP/

########################################
# 안면인식 대상업무 여부 (Y:대상, N:미대상)
#	CASA = 입출금(원화)
#	FCSA = 입출금 (외화)
#	BBCA = 입출금 (개사-다모아비즈)
#	SCSK = 증권 (원화)
#	SCSF = 증권 (외화)
#	TRLR = 이체한도
#	MOTP = 모바일 OTP 발급/재발급
#	MOLR = OTP/보안카드 오류해제
#	MHLR = 휴면계좌 활성화
#	MPLR = 계좌 비밀번호 재설정
#	MBAC = 전자금융 기본계좌 변경
#	MPRS = 로그인 비밀번호 재설정
#	MACC = 출금계좌 변경등록
#	INBK = 회원가입
#	OPPL = SC제일 신용대출
#	NSPL = 새희망홀씨2
#	MAPL = 모바일소액대출
#	MRAS = 화상상담
#	MCDD = 고객확인제도/CDD
#	DRPL = 신용대출연기갱신(CDD 신분증징구를위함)
#	CMJG = 전세보증론(CDD 신분증징구를위함)
#	CMJL = 전세보증론연기(CDD 신분증징구를위함)
########################################
FACE_TARGET_CASA = Y
FACE_TARGET_FCSA = Y
FACE_TARGET_BBCA = Y
FACE_TARGET_SCSK = Y
FACE_TARGET_SCSF = Y
FACE_TARGET_TRLR = Y
FACE_TARGET_MOTP = Y
FACE_TARGET_MOLR = Y
FACE_TARGET_MHLR = Y
FACE_TARGET_MPLR = Y
FACE_TARGET_MBAC = Y
FACE_TARGET_MPRS = Y
FACE_TARGET_MACC = Y
FACE_TARGET_INBK = Y
FACE_TARGET_OPPL = Y
FACE_TARGET_NSPL = Y
FACE_TARGET_MAPL = Y
FACE_TARGET_MRAS = N
FACE_TARGET_MCDD = Y
FACE_TARGET_DRPL = Y
FACE_TARGET_CMJG = Y
FACE_TARGET_CMJL = Y

########################################
# WEB 안면인식 대상업무 여부 (Y:대상, N:미대상)
#	CASA = 입출금(원화)
#	FCSA = 입출금 (외화)
#	BBCA = 입출금 (개사-다모아비즈)
#	SCSK = 증권 (원화)
#	SCSF = 증권 (외화)
#	TRLR = 이체한도
#	MOTP = 모바일 OTP 발급/재발급
#	MOLR = OTP/보안카드 오류해제
#	MHLR = 휴면계좌 활성화
#	MPLR = 계좌 비밀번호 재설정
#	MBAC = 전자금융 기본계좌 변경
#	MPRS = 로그인 비밀번호 재설정
#	MACC = 출금계좌 변경등록
#	INBK = 회원가입
#	OPPL = SC제일 신용대출
#	NSPL = 새희망홀씨2
#	MAPL = 모바일소액대출
#	MCDD = 고객확인제도/CDD
#	DRPL = 신용대출연기갱신(CDD 신분증징구를위함)
#	CMJG = 전세보증론(CDD 신분증징구를위함)
#	CMJL = 전세보증론연기(CDD 신분증징구를위함)
########################################
WEB_FACE_TARGET_CASA = Y
WEB_FACE_TARGET_FCSA = Y
WEB_FACE_TARGET_BBCA = Y
WEB_FACE_TARGET_SCSK = N
WEB_FACE_TARGET_SCSF = N
WEB_FACE_TARGET_TRLR = N
WEB_FACE_TARGET_MOTP = N
WEB_FACE_TARGET_MOLR = N
WEB_FACE_TARGET_MHLR = N
WEB_FACE_TARGET_MPLR = N
WEB_FACE_TARGET_MBAC = N
WEB_FACE_TARGET_MPRS = N
WEB_FACE_TARGET_MACC = N
WEB_FACE_TARGET_INBK = Y
WEB_FACE_TARGET_OPPL = Y
WEB_FACE_TARGET_NSPL = Y
WEB_FACE_TARGET_MAPL = Y
WEB_FACE_TARGET_MRAS = N
WEB_FACE_TARGET_MCDD = Y
WEB_FACE_TARGET_DRPL = Y
WEB_FACE_TARGET_CMJG = Y
WEB_FACE_TARGET_CMJL = Y

########################################
# 안면인식 5회 실패시 영상통화 진입여부 (Y:대상, N:미대상)
#	CASA = 입출금(원화)
#	FCSA = 입출금 (외화)
#	BBCA = 입출금 (개사-다모아비즈)
#	SCSK = 증권 (원화)
#	SCSF = 증권 (외화)
#	TRLR = 이체한도
#	MOTP = 모바일 OTP 발급/재발급
#	MOLR = OTP/보안카드 오류해제
#	MHLR = 휴면계좌 활성화
#	MPLR = 계좌 비밀번호 재설정
#	MBAC = 전자금융 기본계좌 변경
#	MPRS = 로그인 비밀번호 재설정
#	MACC = 출금계좌 변경등록
#	INBK = 회원가입
########################################
VIDEO_CALL_TARGET_CASA = N
VIDEO_CALL_TARGET_FCSA = N
VIDEO_CALL_TARGET_BBCA = N
VIDEO_CALL_TARGET_SCSK = N
VIDEO_CALL_TARGET_SCSF = N
VIDEO_CALL_TARGET_TRLR = N
VIDEO_CALL_TARGET_MOTP = N
VIDEO_CALL_TARGET_MOLR = N
VIDEO_CALL_TARGET_MHLR = N
VIDEO_CALL_TARGET_MPLR = N
VIDEO_CALL_TARGET_MBAC = N
VIDEO_CALL_TARGET_MPRS = N
VIDEO_CALL_TARGET_MACC = N
VIDEO_CALL_TARGET_INBK = N
VIDEO_CALL_TARGET_MRAS = N
########################################
#V3Mobile Web Info
# V3_MOBILE_WEB_SWITCH - V3 모바일앱 실행 유무 ( Y or N )
# V3_MOBILE_DETECT_AI - 악성앱 검사 유무 ( Y or N )
# V3_MOBILE_DETECT_DI - 단말 정보 검사 유무 ( Y or N )
# V3_MOBILE_DETECT_RC - 루팅 검사 유무 ( Y or N )
# V3_MOBILE_DETECT_TI - 단말 위협 정보 검사 유무 ( Y or N )
# V3_MOBILE_REALTIME_AI - 실시간 악성 검사 유무 ( Y or N )
# V3_MOBILE_REALTIME_RC - 실시간 루팅/원격 검사 유무 ( Y or N )
########################################
V3_MOBILE_WEB_LICENSEKEY = U6FF-PU66-3DP2-FUB8-59RM
V3_MOBILE_WEB_SWITCH = Y
V3_MOBILE_DETECT_AI = Y
V3_MOBILE_DETECT_DI = Y
V3_MOBILE_DETECT_RC = Y
V3_MOBILE_DETECT_TI = Y
V3_MOBILE_REALTIME_AI = Y
V3_MOBILE_REALTIME_RC = Y
V3_MOBILE_SYMMETRIC_KEY = ScV3MobileAPPKey

#알체라 서버(개발)
ALCHERA_SERVER_BASE_URL = https://ssatest.sc.co.kr:19413
#ALCHERA_SERVER_BASE_URL = http://10.61.17.91:9050
#ALCHERA_SERVER_BASE_URL = https://alchera_UT.sc.co.kr:19413
ALCHERA_CLIENT_LICENSE_KEY = FPkTF4AaphojyNnvXGBNJGy/Ia9gksKwQUrdvHauSV0Q33he1emOT+zDkH8DVM4PEP1SZK1adCdmDjFyK4ytWBBO4O09ph4n1Ri93Xx8jOSNLhhMwpuq7jzcwoZcytcVZPiSAx/0Lp0k735nFfSesFKCgfdv6DgQOeHP32dyW9AtEigcf/ehF8qvY3Zc3alMDGRTy9HS7h6NMLX6g06VKlQQEBucSl1uuN+3n+zd3F5EAEgvkgZD4AA6l7/AH1NzVUAyoUKlLg8me6+1nPfEJnQyKje1I0+/sy4sjaXymLsJRvM79pZKB47xHx3L6YLfqF3UW6mnY2Y48EnUSxmOz3dkcIGPAus53THhQvC4jPTftVMk0A5eBevyIIA1j3Qs4FDXbuvDmtLWssOjTzgZpFpyzwe4DQWqRRvIrMAsG2Fj1TR56k6En1YRWf1RnlN+3qaRX7fsTyyl/XkZyu6IBH644CiLr4At8EqEkDbGFMgLL3qjymdLdTbIwJsyI6bZavObcHhHPgTHz6LF76PsNkiWuBA==


#알체라 서버(안면인식)
#ALCHERA_FACE_SERVER_BASE_URL = http://10.61.17.91:9820
ALCHERA_FACE_SERVER_BASE_URL = https://ssatest.sc.co.kr:19513
#ALCHERA_FACE_SERVER_BASE_URL = http://ssatest.sc.co.kr:9150