
# MESSAGE HUB FDS LOG SERVER
message-hub.log.server.ip = 10.61.17.101
message-hub.log.server.port = 6601
#message-hub.log.server.ip = 127.0.0.1
#message-hub.log.server.port = 9090



#금결원 연동 API
openapi.prop.kftc.name=kftc.open-platform

#kftc.open-platform
kftc.open-platform.api.client_id = br8oNRlSwcOFYb9EkNt/7Hdh2qmvpV9Gmq363v+s0fA=
kftc.open-platform.api.client_secret = 8UmqmV48DhnYnC/flaGEwbSb0G3PjPxvHmjYOIJQuAI=

# 초기인증
#kftc.open-platform.api.base.url = http://localhost:9080
#kftc.open-platform.api.base.url = http://10.61.17.91:9683
kftc.open-platform.api.base.url = https://10.61.222.42:10443
#kftc.open-platform.api.base.url = http://10.61.222.42:10080
kftc.open-platform.api.TOKEN.url = /oauth/2.0/token
kftc.open-platform.api.TOKEN.method = POST

#사용자정보조회
kftc.open-platform.api.USER_ME.url = /v2.0/user/me
kftc.open-platform.api.USER_ME.method = GET

#계좌해지
kftc.open-platform.api.ACCOUNT_LIST.url = /v2.0/account/list
kftc.open-platform.api.ACCOUNT_LIST.method = GET

#계좌해지
kftc.open-platform.api.ACCOUNT_CANCEL.url = /v2.0/account/cancel
kftc.open-platform.api.ACCOUNT_CANCEL.method = POST

#사용자계좌등록
kftc.open-platform.api.USER_REGISTER.url = /v2.0/user/register
kftc.open-platform.api.USER_REGISTER.method = POST

#잔액조회#1
kftc.open-platform.api.ACCOUNT_BALANCE_FINNUM.url = /v2.0/account/balance/fin_num
kftc.open-platform.api.ACCOUNT_BALANCE_FINNUM.method = GET

#잔액조회#2
kftc.open-platform.api.ACCOUNT_BALANCE_ACNTNUM.url = /v2.0/account/balance/acnt_num
kftc.open-platform.api.ACCOUNT_BALANCE_ACNTNUM.method = POST

#거래내역조회#1
kftc.open-platform.api.ACCOUNT_TRANSACTIONLIST_FINNUM.url = /v2.0/account/transaction_list/acnt_num
kftc.open-platform.api.ACCOUNT_TRANSACTIONLIST_FINNUM.method = GET

#거래내역조회#2
kftc.open-platform.api.ACCOUNT_TRANSACTIONLIST_ACNTNUM.url = /v2.0/account/transaction_list/acnt_num
kftc.open-platform.api.ACCOUNT_TRANSACTIONLIST_ACNTNUM.method = POST

#계좌실명조회
kftc.open-platform.api.INQUIRY_REALNAME.url = /v2.0/inquiry/real_name
kftc.open-platform.api.INQUIRY_REALNAME.method = POST

#송금인정보조회
kftc.open-platform.api.INQUIRY_REMITLIST.url = /v2.0/inquiry/remit_list
kftc.open-platform.api.INQUIRY_REMITLIST.method = POST

#출금이체#1
kftc.open-platform.api.TRANSFER_WITHDRAW_FINNUM.url = /v2.0/transfer/withdraw/fin_num
kftc.open-platform.api.TRANSFER_WITHDRAW_FINNUM.method = POST

#출금이체#2
kftc.open-platform.api.TRANSFER_WITHDRAW_ACNTNUM.url = /v2.0/transfer/withdraw/acnt_num
kftc.open-platform.api.TRANSFER_WITHDRAW_ACNTNUM.method = POST

#입금이체#1
kftc.open-platform.api.TRANSFER_DEPOSIT_FINNUM.url = /v2.0/transfer/deposit/fin_num
kftc.open-platform.api.TRANSFER_DEPOSIT_FINNUM.method = POST

#입금이체#2
kftc.open-platform.api.TRANSFER_DEPOSIT_ACNTNUM.url = /v2.0/transfer/deposit/acnt_num
kftc.open-platform.api.TRANSFER_DEPOSIT_ACNTNUM.method = POST

#이체결과조회
kftc.open-platform.api.TRANSFER_RESULT.url = /v2.0/transfer/result
kftc.open-platform.api.TRANSFER_RESULT.method = POST

#수취조회
kftc.open-platform.api.INQUIRY_RECEIVE.url = /v2.0/inquiry/receive
kftc.open-platform.api.INQUIRY_RECEIVE.method = POST

#제3자정보제공동의
kftc.open-platform.api.USER_REAGMT.url = /v2.0/user/re_agmt
kftc.open-platform.api.USER_REAGMT.method = POST

##########################
#실시간 재입금API여부
kftc.open-platform.real.REDEPOSIT_TRANSFER_YN=N
##########################

#SC제일은행 이체 계정계좌
##약정계좌/계정구분 N:계좌, C:계정
kftc.open-platform.api.CNTR_ACCOUNT_TYPE=C
##약정계좌/계정번호
kftc.open-platform.api.CNTR_ACCOUNT_NUM=003661
##이체용도(TR:송금, ST:결제, RC:충전)
kftc.open-platform.api.TRANSFER_PURPOSE=TR
##약정계좌/계정번호 > 입금계좌인자내용 > 사용안함 직접입력 또는 고객명
kftc.open-platform.api.DPS_PRINT_CONTENT=SC제일은행오픈뱅킹
##약정계좌/계정번호 > 출금계좌인자내용
kftc.open-platform.api.WD_PRINT_CONTENT=SC제일은행오픈뱅킹
##입금이체용 암호문구(테스트:NONE, 운영:미정-전용선일경우 'NONE')
kftc.open-platform.api.WD_PASS_PHRASE=NONE
##[결번배치, 실시간 재입금] 재입금처리시 수취인성명 검증 여부 (on:검증, off:미검증)
kftc.open-platform.api.RE_DPS_NAME_CHECK_OPTION=on
##[결번배치] 에러발생시 SMS발송 대상자 (관리자휴대번호). 2022.02 이행
kftc.open-platform.magager.sms.callphone=01071263809;01093746768;01035895842;01029103631;01044221311;01091464816;01099058368;01042488424;01040073187;01029056762;01093349313

#토큰 재발급 (배치) 에러발생시 SMS발송 대상자 (관리자휴대번호)
kftc.open-platform.batch.sms.callphone=01091464816;01093349313;01042488424;01029056762;01029103631;01099058368;01040073187;01044221311;01035895842;01024208707