#secondfinance 서버 API 통신 IP
secondfinance.api.url=https://10.61.222.42:10543


#secondfinance 서버 API 통신 baseURL
secondfinance.api.baseurl=https://10.61.222.42:10543

#secondfinance 서버 통신 svc_id
secondfinance.api.svc_id=

#secondfinance 서버 통신 svc_cert_key
secondfinance.api.svc_cert_key=


#secondfinance 웰컴 가상담 API
secondfinance.api.WelCome.url = /WelB/ib20/fil/IBNAPISCJ001_00AM
secondfinance.api.WelCome.method = POST
secondfinance.api.WelCome.host= wwwd.welcomebank.co.kr

#secondfinance 웰컴 상태 조회 API
secondfinance.api.WelComeInq.url = /WelB/ib20/fil/IBNAPISCJ002_00AM
secondfinance.api.WelComeInq.method = POST
secondfinance.api.WelComeInq.host= wwwd.welcomebank.co.kr

#secondfinance 웰컴 배치 조회 API
secondfinance.api.WelComeBatch.url = /WelB/ib20/fil/IBNAPISCJ003_00AM
secondfinance.api.WelComeBatch.method = POST
secondfinance.api.WelComeBatch.host= wwwd.welcomebank.co.kr

#secondfinance JB우리캐피탈 가상담 API
secondfinance.api.WooC.url = /WooC/scbankLoanLim.jsp
secondfinance.api.WooC.method = POST
secondfinance.api.WooC.host= detc.wooricap.com

#secondfinance JB우리캐피탈 가상담 API
secondfinance.api.WooCInq.url = /WooC/scbankLoanStatIqry.jsp
secondfinance.api.WooCInq.method = POST
secondfinance.api.WooCInq.host= detc.wooricap.com

#secondfinance JB우리캐피탈 가상담 API
secondfinance.api.WooCBatch.url = /WooC/scbankBatchIqry.jsp
secondfinance.api.WooCBatch.method = POST
secondfinance.api.WooCBatch.host=detc.wooricap.com

#secondfinance 렌딧 가상담 API
secondfinance.api.LenD.url = /LenD/api/offer-inquiry/scbank/inquiry
secondfinance.api.LenD.method = POST
secondfinance.api.LenD.host= loan-hub-internal-sc-dev.lendit.co.kr

#secondfinance 렌딧 상태 조회 API
secondfinance.api.LenDInq.url = /LenD/api/offer-inquiry/scbank/status-inquiry
secondfinance.api.LenDInq.method = POST
secondfinance.api.LenDInq.host= loan-hub-internal-sc-dev.lendit.co.kr

#secondfinance 렌딧 배치 조회 API
secondfinance.api.LenDBatch.url = /LenD/api/offer-inquiry/scbank/batch/status-inquiry
secondfinance.api.LenDBatch.method = POST
secondfinance.api.LenDBatch.host= loan-hub-internal-sc-dev.lendit.co.kr

#secondfinance 유진 가상담 API
secondfinance.api.EugB.url = /EugB/scbank_getlimit
secondfinance.api.EugB.method = POST
secondfinance.api.EugB.host= www.hdsb-agent.com

#secondfinance 유진 상태 조회 API
secondfinance.api.EugBInq.url = /EugB/scbank_getstatus
secondfinance.api.EugBInq.method = POST
secondfinance.api.EugBInq.host= www.hdsb-agent.com

#secondfinance 유진 배치 조회 API
secondfinance.api.EugBBatch.url = /EugB/scbank_getbatch
secondfinance.api.EugBBatch.method = POST
secondfinance.api.EugBBatch.host= www.hdsb-agent.com

#secondfinance 대신 가상담 API
secondfinance.api.DaiB.url = /DaiB/dsbankApi/bank/sc/prescreening
secondfinance.api.DaiB.method = POST
secondfinance.api.DaiB.host= dev-inv-bank.daishin.com

#secondfinance 대신 상태 조회 API
secondfinance.api.DaiBInq.url = /DaiB/dsbankApi/bank/sc/status
secondfinance.api.DaiBInq.method = POST
secondfinance.api.DaiBInq.host= dev-inv-bank.daishin.com

#secondfinance 대신 배치 조회 API
secondfinance.api.DaiBBatch.url = /DaiB/dsbankApi/bank/sc/status/batch
secondfinance.api.DaiBBatch.method = POST
secondfinance.api.DaiBBatch.host= dev-inv-bank.daishin.com