#토스접속경로
toss.cnnctn_way=000120

#토스관리점번호
toss.branch_no=860

#토스소개자행번
toss.clerk_no=167843

#토스상품아이디
toss.product_id=8989

#토스상품명
toss.product_name=SC제일 토스 소액 대출

#토스업무구분
toss.biz_type=MAPL

#토스 전자서명 유효시간 (default - 3600초/1시간)--당행앱 세션 time 10분.
toss.SIGN_EXPIRE_SECONDS=600

#########################[이하] TOSS OUT BOUND API 관련 내용#########################
#toss.outbound
#toss.outbound.api.base.url=https://10.61.222.42:10543
toss.outbound.api.base.url=http://10.61.222.42:10180

#toss.outbound auth token(Toss에서 발급한 AccessToken)
toss.outbound.api.AUTH_TOKEN=6b54c866-6c2d-4292-8b2a-70ff9e5e0d78

#거래정보 조회API (휴대폰본인인증 전에 실행.)
toss.outbound.api.TRAD_INFO_INQ.url=/loan-rep/api/v1/partner/applicant-info
toss.outbound.api.TRAD_INFO_INQ.method=POST
toss.outbound.api.TRAD_INFO_INQ.host=loan-rep.alpha.toss.bz

#대출상태 업데이트API
toss.outbound.api.TRAD_STAT_UPD.url=/loan-rep/api/v1/partner/update-status
toss.outbound.api.TRAD_STAT_UPD.method=POST
toss.outbound.api.TRAD_STAT_UPD.host=loan-rep.alpha.toss.bz

#(복수)서명요청API
toss.outbound.api.SIGN_DOCS_REQ.url=/api-dedicate/scBank/v1/sign/docs/request
toss.outbound.api.SIGN_DOCS_REQ.method=POST
toss.outbound.api.SIGN_DOCS_REQ.host=cert.alpha.toss.bz

#(복수)서명결과API
toss.outbound.api.SIGN_DOCS_RES.url=/api-dedicate/scBank/v1/sign/docs/result
toss.outbound.api.SIGN_DOCS_RES.method=POST
toss.outbound.api.SIGN_DOCS_RES.host=cert.alpha.toss.bz
#########################[이상] TOSS OUT BOUND API 관련 내용#########################

#########################[이하] TOSS ACCT OUT BOUND API 관련 내용####################
#CASA상태 업데이트API(DEV)
toss.outbound.api.TRAD_CASA_STAT_UPD.url=/ads-account/api-public/v1/callbacks/bank/23/complete-create-account
toss.outbound.api.TRAD_CASA_STAT_UPD.method=POST
toss.outbound.api.TRAD_CASA_STAT_UPD.host=ads-account-api.alpha.toss.bz
#########################[이상] TOSS ACCT OUT BOUND API 관련 내용####################