package com.scbank.process.api.svc.shared.components.customer.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import com.scbank.process.api.edmi.dto.oltp.CbIbk01H92000Res;
import com.scbank.process.api.edmi.dto.oltp.CbIbk01H92C00Res;
import com.scbank.process.api.edmi.dto.oltp.CbIbk01H92C01Req;
import com.scbank.process.api.svc.shared.components.customer.dto.CustCddInfoInquiryResponse;
import com.scbank.process.api.svc.shared.components.customer.dto.RegistCustInfoRequest;
import com.scbank.process.api.svc.shared.components.customer.dto.RegistCustInfoResponse;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface CddInfoMapper {
	
	@Mapping(source = "yiIDGB", target = "YIIDGB", defaultValue = "")
	@Mapping(source = "yiJHGB", target = "YIJHGB", defaultValue = "")
	@Mapping(source = "yiCMFJN", target = "YICMFJN", defaultValue = "")
	@Mapping(source = "yiENGNA", target = "YIENGNA", defaultValue = "")
	@Mapping(source = "yiUPSRGB", target = "YIUPSRGB", defaultValue = "")
	@Mapping(source = "yiHMUPNO", target = "YIHMUPNO", defaultValue = "")
	@Mapping(source = "yiHMJSO1", target = "YIHMJSO1")
	@Mapping(source = "yiHMJSO2", target = "YIHMJSO2")
	@Mapping(source = "yiTELRGN1", target = "YITELRGN1", defaultValue = "")
	@Mapping(source = "yiTELK1", target = "YITELK1", defaultValue = "")
	@Mapping(source = "yiTEL1", target = "YITEL1", defaultValue = "")
	@Mapping(source = "yiOFIUPNO", target = "YIOFIUPNO", defaultValue = "")
	@Mapping(source = "yiOFIJSO1", target = "YIOFIJSO1")
	@Mapping(source = "yiOFIJSO2", target = "YIOFIJSO2")
	@Mapping(source = "yiTELRGN2", target = "YITELRGN2", defaultValue = "")
	@Mapping(source = "yiTELK2", target = "YITELK2", defaultValue = "")
	@Mapping(source = "yiTEL2", target = "YITEL2", defaultValue = "")
	@Mapping(source = "yiMBRGN", target = "YIMBRGN", defaultValue = "")
	@Mapping(source = "yiMBK", target = "YIMBK", defaultValue = "")
	@Mapping(source = "yiMBTEL", target = "YIMBTEL", defaultValue = "")
	@Mapping(source = "yiEMALJSO", target = "YIEMALJSO", defaultValue = "")
	@Mapping(source = "yiGSEGB", target = "YIGSEGB", defaultValue = "")
	@Mapping(source = "yiGRJGB", target = "YIGRJGB", defaultValue = "")
	@Mapping(source = "yiJOBCOD", target = "YIJOBCOD", defaultValue = "")
	@Mapping(source = "yiSDJGB", target = "YISDJGB", defaultValue = "")
	@Mapping(source = "yiCLDGBCOD", target = "YICLDGBCOD", defaultValue = "")
	@Mapping(source = "yiWEDYMCOD", target = "YIWEDYMCOD", defaultValue = "")
	@Mapping(source = "yiJSCDGB1", target = "YIJSCDGB1", defaultValue = "")
	@Mapping(source = "yiJSCD4", target = "YIJSCD4", defaultValue = "")
	@Mapping(source = "yiJUSO4", target = "YIJUSO4")
	@Mapping(source = "yiZIP41", target = "YIZIP41", defaultValue = "")
	@Mapping(source = "yiZIP42", target = "YIZIP42", defaultValue = "")
	@Mapping(source = "yiZIP43", target = "YIZIP43", defaultValue = "")
	@Mapping(source = "yiZIP44", target = "YIZIP44", defaultValue = "")
	@Mapping(source = "yiJSCDGB2", target = "YIJSCDGB2", defaultValue = "")
	@Mapping(source = "yiJSCD5", target = "YIJSCD5", defaultValue = "")
	@Mapping(source = "yiJUSO5", target = "YIJUSO5")
	@Mapping(source = "yiZIP51", target = "YIZIP51", defaultValue = "")
	@Mapping(source = "yiZIP52", target = "YIZIP52", defaultValue = "")
	@Mapping(source = "yiZIP53", target = "YIZIP53", defaultValue = "")
	@Mapping(source = "yiZIP54", target = "YIZIP54", defaultValue = "")
	@Mapping(source = "yiKUK", target = "YIKUK", defaultValue = "")
	@Mapping(source = "yiOFINA", target = "YIOFINA", defaultValue = "")
	@Mapping(source = "yiDPTNA", target = "YIDPTNA", defaultValue = "")
	@Mapping(source = "yiJWINA1", target = "YIJWINA1", defaultValue = "")
	@Mapping(source = "yiPAGI", target = "YIPAGI", defaultValue = "")
	@Mapping(source = "yiEADGB", target = "YIEADGB", defaultValue = "")
	@Mapping(source = "yiEJUSO1", target = "YIEJUSO1", defaultValue = "")
	@Mapping(source = "yiEJUSO2", target = "YIEJUSO2", defaultValue = "")
	@Mapping(source = "yiEBUNHO", target = "YIEBUNHO", defaultValue = "")
	@Mapping(source = "yiENAYN", target = "YIENAYN", defaultValue = "")
	@Mapping(source = "yiENAME", target = "YIENAME", defaultValue = "")
	@Mapping(source = "yiJOBDEL", target = "YIJOBDEL", defaultValue = "")
	CbIbk01H92C01Req toCbIbk01H92C01ReqDto(RegistCustInfoRequest request);
	
	
	@Mapping(source = "YOADRGB1", target = "yoADRGB1")
	@Mapping(source = "YOZIPTXT1", target = "yoZIPTXT1")
	@Mapping(source = "YOZIPCD40", target = "yoZIPCD40")
	@Mapping(source = "YOZIPCD41", target = "yoZIPCD41")
	@Mapping(source = "YOZIPCD42", target = "yoZIPCD42")
	@Mapping(source = "YOZIPCD43", target = "yoZIPCD43")
	@Mapping(source = "YOZIPCD44", target = "yoZIPCD44")
	@Mapping(source = "YOSJUSO4", target = "yoSJUSO4")
	@Mapping(source = "YOJUSO4", target = "yoJUSO4")
	@Mapping(source = "YOJIKGB", target = "yoJIKGB")
	@Mapping(source = "YOJUSOK2", target = "yoJUSOK2")
	@Mapping(source = "YOJIKCD40", target = "yoJIKCD40")
	@Mapping(source = "YOJIKCD41", target = "yoJIKCD41")
	@Mapping(source = "YOJIKCD42", target = "yoJIKCD42")
	@Mapping(source = "YOJIKCD43", target = "yoJIKCD43")
	@Mapping(source = "YOJIKCD44", target = "yoJIKCD44")
	@Mapping(source = "YOJIKDORO", target = "yoJIKDORO")
	@Mapping(source = "YOJIKSANG", target = "yoJIKSANG")
	@Mapping(source = "YOENAME", target = "yoENAME")
	@Mapping(source = "YOOGKCD", target = "yoOGKCD")
	@Mapping(source = "YOOBIRNC", target = "yoOBIRNC")
	@Mapping(source = "YOEJUSO1", target = "yoEJUSO1")
	@Mapping(source = "YOEBUNHO", target = "yoEBUNHO")
	@Mapping(source = "YOFXYN", target = "yoFXYN")
	@Mapping(source = "YOEADGB", target = "yoEADGB")
	@Mapping(source = "YOGEOJU", target = "yoGEOJU")
	@Mapping(source = "YOOFAGKCD", target = "yoOFAGKCD")
	@Mapping(source = "YOOFTGKCD", target = "yoOFTGKCD")
	RegistCustInfoResponse toRegistCustInfoResponseDto(CbIbk01H92000Res response);
	
	@Mapping(source = "YOUSID", target = "yoUsId")
    @Mapping(source = "YOIDGB", target = "yoIdGb")
    @Mapping(source = "YOJHGB", target = "yoJhGb")
    @Mapping(source = "YOJMNO", target = "yoJmNo")
    @Mapping(source = "YOEXIST", target = "yoExist")
    @Mapping(source = "YOWORKER", target = "yoWorker")
    @Mapping(source = "YOCDDOK", target = "yoCddOk")
    @Mapping(source = "YOOJUM", target = "yoOjum")
    @Mapping(source = "YOOCMFNO", target = "yoOcmfNo")
    @Mapping(source = "YOSUSIN", target = "yoSusin")
    @Mapping(source = "YOIBUSER", target = "yoIbUser")
    @Mapping(source = "YOEMAIL", target = "yoEmail")
    @Mapping(source = "YOHDDD", target = "yoHddd")
    @Mapping(source = "YOHGUK", target = "yoHguk")
    @Mapping(source = "YOHTEL", target = "yoHtel")
    @Mapping(source = "YOFXYN", target = "yoFxYn")
    @Mapping(source = "YOGJGB", target = "yoGjGb")
    @Mapping(source = "YOCCGB", target = "yoCcGb")
    @Mapping(source = "YOPAGIHJ", target = "yoPagiHj")
    @Mapping(source = "YODUMMY", target = "yoDummy")
    @Mapping(source = "YOOGKCD", target = "yoOGkCd")
    @Mapping(source = "YOOCDDNI", target = "yoOCddNi")
    @Mapping(source = "YOOBIRNC", target = "yoOBirNc")
    @Mapping(source = "YOOFAGKCD", target = "yoOFaGkCd")
    @Mapping(source = "YOOFTGKCD", target = "yoOFtGkCd")
    @Mapping(source = "YOFIRST", target = "yoFirst")
    @Mapping(source = "YOCDDPGJ", target = "yoCddPgj")
    @Mapping(source = "YOCDDKYCLV", target = "yoCddKycLv")
    @Mapping(source = "YOCDDKYCLC", target = "yoCddKycLc")
    @Mapping(source = "YONTBYN", target = "yoNtbYn")
    @Mapping(source = "YOCDDRV", target = "yoCddRv")
    @Mapping(source = "YOCDDILJA", target = "yoCddIlja")
    @Mapping(source = "YODUMMY2", target = "yoDummy2")
    @Mapping(source = "YOEADGB", target = "yoEAdGb")
    @Mapping(source = "YOEJUSO1", target = "yoEJuso1")
    @Mapping(source = "YOEJUSO2", target = "yoEJuso2")
    @Mapping(source = "YOGEOJU", target = "yoGeoju")
    @Mapping(source = "YOGEORE", target = "yoGeore")
    @Mapping(source = "YOIBJMGB", target = "yoIbJmGb")
    @Mapping(source = "YOGUNSU", target = "yoGunsu")
    @Mapping(source = "YOGUNSU_REC", target = "yoGunsuRec")
    @Mapping(source = "YOMSSU", target = "yoMssu")
    @Mapping(source = "YOMSSU_REC", target = "yoMssuRec")
	CustCddInfoInquiryResponse toCustCddInfoResponseDto(CbIbk01H92C00Res response);
	
	@Mapping(source = "YOSASAUP", target = "yoSaSaup")
    @Mapping(source = "YOSANAME", target = "yoSaName")
    @Mapping(source = "YOSAENAME", target = "yoSaEname")
    @Mapping(source = "YOSASINUP", target = "yoSaSinUp")
	CustCddInfoInquiryResponse.yoGunsuRecGrid toCustCddInfoResponseDto(CbIbk01H92C00Res.YOGUNSU_REC_GRID recList);
	
	@Mapping(source = "YOACMFBR", target = "yoACmfBr")
    @Mapping(source = "YOACMFNO", target = "yoACmfNo")
    @Mapping(source = "YOADUMMY", target = "yoADummy")
	CustCddInfoInquiryResponse.yoMssuRecGrid toCustCddInfoResponseDto(CbIbk01H92C00Res.YOMSSU_REC_GRID recList);
	
}
