###########
# 방문판매 API 서버 UT <> SIT 변경 시 PMS에서 토큰재발급 해주자
# PMS3.0 > 서비스관리 > 방문판매재발급
###########

#방문판매 서버 API 통신 API baseURL
#d2d.api.url=https://OnExtAPIGWUT:8443
#d2d.api.url=https://apiinttest.standardcharteredad.co.kr:8443
d2d.api.url=https://apiinttest.standardcharteredad.co.kr:9443

#방문판매 서버 API 통신 API baseURL
#d2d.api.baseurl=https://apiinttest.standardcharteredad.co.kr:8443
d2d.api.baseurl=https://apiinttest.standardcharteredad.co.kr:9443

#방문판매 서버 API 통신 svc_id
d2d.api.svc_id=

#방문판매 서버 API 통신 svc_cert_key
d2d.api.svc_cert_key=


#방문판매 - 토큰발급 API
d2d.api.TOKEN_DATA.url = /d2d/oauth2/token
d2d.api.TOKEN_DATA.method = POST
d2d.api.TOKEN_DATA.host=

#방문판매 - 사전안내 리스트 조회 API
d2d.api.MANAGE_INFO_LIST.url = /d2d/sc/d2d/mobile/manage-info-list
d2d.api.MANAGE_INFO_LIST.method = GET
d2d.api.MANAGE_INFO_LIST.host=

#방문판매 - 고객 적합성 적정성 진행여부 저장 API
d2d.api.CUSTOMER_PROPER.url = /d2d/sc/d2d/mobile/customer/proper
d2d.api.CUSTOMER_PROPER.method = PATCH
d2d.api.CUSTOMER_PROPER.host=

#방문판매 - 고객정보생성 API
d2d.api.CUSTOMER_INFO_CREATE.url = /d2d/sc/d2d/mobile/customer
d2d.api.CUSTOMER_INFO_CREATE.method = POST
d2d.api.CUSTOMER_INFO_CREATE.host=

#방문판매 - 고객 동의정보 갱신 API
d2d.api.MANAGE_CHANGE_STATUS.url = /d2d/sc/d2d/mobile/customer/agreement
d2d.api.MANAGE_CHANGE_STATUS.method = PATCH
d2d.api.MANAGE_CHANGE_STATUS.host=


#방문판매 - 사전안내 상세조회 API
d2d.api.MANAGE_INFO_DETAIL.url = /d2d/sc/d2d/mobile/manage-info
d2d.api.MANAGE_INFO_DETAIL.method = GET
d2d.api.MANAGE_INFO_DETAIL.host=

#방문판매 - 본인인증 결과 저장
d2d.api.SELF_AUTH_HISTORY.url = /d2d/sc/d2d/mobile/customer/auth-history
d2d.api.SELF_AUTH_HISTORY.method = POST
d2d.api.SELF_AUTH_HISTORY.host=
