#금융결제원 클라우드 서버 API 통신 URL
#KFTCFinCert.auth.api.URL=https://10.61.222.42:10443
KFTCFinCert.auth.api.URL=https://krcalabp31:10443

#금융결제원 클라우드 서버 API 사용자 확인(Request Vaildation) URL
KFTCFinCert.auth.token.oauth.URL=/oauth/2.0/token

#금융결제원 클라우드 서버 API 대체인증(MO생략) 허가코드 발급
KFTCFinCert.auth.token.subauth.URL=/v1/users/sub-auth

#금융결제원 클라우드 서버 API 통신 Method
KFTCFinCert.auth.token.common.METHOD=POST

#금융결제원 클라우드 서버 API 통신 HTTP HEADER 타입			            
KFTCFinCert.auth.token.common.CONTENT_TYPE=application/x-www-form-urlencoded;charset=UTF-8

#금융결제원 클라우드 서버 API 통신 클라이언트ID
KFTCFinCert.auth.token.common.CLIENT_ID=ad61d665-46ec-4e5d-9a9f-9ef272ca25ed

#금융결제원 클라우드 서버 API 통신 클라이언트 비밀값?
KFTCFinCert.auth.token.common.CLIENT_SECRET=71d28ceb-e35a-46ff-87b9-ee64b615804c

#금융결제원 클라우드 서버 API 통신 이용기관코드
KFTCFinCert.auth.token.common.ORG_CODE=0023

#금융결제원 클라우드 서버 API 통신 인증 요청 종류
KFTCFinCert.auth.token.common.GRANT_TYPE=client_credentials

#금융결제원 클라우드 서버 API 통신 권한 범위
KFTCFinCert.auth.token.common.SCOPE=cld_auth

#금융결제원 클라우드 서버 API 통신 발급한 토큰의 종류
KFTCFinCert.auth.token.common.TOKEN_TYPE=Bearer
