###########
# mydata API 서버 UT <> SIT 변경 시 PMS에서 토큰재발급 해주자
# PMS3.0 > 서비스관리 > 토큰재발급
###########

#mydata 서버 API 통신 API baseURL - UT(10.62.151.149), SIT(10.62.153.149), UAT(10.62.155.149)
mydata.api.url=https://apicloudinut.standardchartered.co.kr:8443
#mydata.api.url=https://10.62.153.149:8443
#mydata.api.url=https://10.62.155.149:8443

#mydata 서버 API 통신 API baseURL - UT(10.62.151.149), SIT(10.62.153.149), UAT(10.62.155.149)
mydata.api.baseurl=https://apicloudinut.standardchartered.co.kr:8443
#mydata.api.baseurl=https://10.62.153.149:8443
#mydata.api.baseurl=https://10.62.155.149:8443

#mydata 서버 API 통신 API baseURL(공공데이터-AS-IS KONG 으로 전송) UT(10.62.151.149), SIT(10.62.153.149), UAT(10.62.155.149)
mydata.api.pub.url=https://apicloudinut.standardchartered.co.kr:8443
#mydata.api.pub.url=https://10.62.153.149:8443
#mydata.api.pub.url=https://10.62.155.149:8443

#mydata 서버 API 통신 API(mydata api pub baseurl) - 공공데이터-AS-IS KONG 으로 전송 - UT(10.62.151.149), SIT(10.62.153.149), UAT(10.62.155.149)
mydata.api.pub.baseurl=https://apicloudinut.standardchartered.co.kr:8443
#mydata.api.pub.baseurl=https://10.62.153.149:8443
#mydata.api.pub.baseurl=https://10.62.155.149:8443

#mydata 서버 API 통신 svc_id
mydata.api.svc_id=

#mydata 서버 API 통신 svc_cert_key
mydata.api.svc_cert_key=

#mydata - 토큰발급 API
mydata.api.TOKEN_DATA.url = /sc/oauth2-jwt/token
mydata.api.TOKEN_DATA.method = POST
mydata.api.TOKEN_DATA.host=

#mydata - 토큰삭제 API
mydata.api.TOKENDEL_DATA.url = /sc/oauth2-jwt-token/
mydata.api.TOKENDEL_DATA.method = POST
mydata.api.TOKENDEL_DATA.host=

#제공 - 본인인증 API
mydata.api.AUTHORIZE_DATA.url = /sc/offer/authorize
mydata.api.AUTHORIZE_DATA.method = POST
mydata.api.AUTHORIZE_DATA.host=

#제공 - 계좌목록조회 API
mydata.api.ACCOUNT_DATA.url = /sc/offer/accounts
mydata.api.ACCOUNT_DATA.method = POST
mydata.api.ACCOUNT_DATA.host=

#제공 - 개인신용정보 전송요구 API
mydata.api.CONSENTS_DATA.url = /sc/offer/consents
mydata.api.CONSENTS_DATA.method = POST
mydata.api.CONSENTS_DATA.host=

#이용 - 기관별 잔액 조회 API
mydata.api.USEAMT_DATA.url = /sc/use/org/amt
mydata.api.USEAMT_DATA.method = POST
mydata.api.USEAMT_DATA.host=

#이용 - 전송요구내역 확인 API
mydata.api.AUTHORGS_DATA.url = /sc/auth/orgs
mydata.api.AUTHORGS_DATA.method = POST
mydata.api.AUTHORGS_DATA.host=

#이용 - 통합인증 전송요구 API
mydata.api.CONSENTSREQ_DATA.url = /sc/auth/intgrt/consents/req
mydata.api.CONSENTSREQ_DATA.method = POST
mydata.api.CONSENTSREQ_DATA.host=

#이용 - 통합인증 자산목록조회 API
mydata.api.CONSENTSLIST_DATA.url = /sc/use/intgrt/consents/list
mydata.api.CONSENTSLIST_DATA.method = POST
mydata.api.CONSENTSLIST_DATA.host=

#이용 - 통합인증 전송요구 API
mydata.api.CONSENTSDTRMNTN_DATA.url = /sc/auth/intgrt/consents/dtrmntn
mydata.api.CONSENTSDTRMNTN_DATA.method = POST
mydata.api.CONSENTSDTRMNTN_DATA.host=

#이용 - 전송완료 확인 API
mydata.api.ORGSTOKEN_DATA.url = /sc/auth/orgs/token
mydata.api.ORGSTOKEN_DATA.method = POST
mydata.api.ORGSTOKEN_DATA.host=

#이용 - 실패기관 재전송 API
mydata.api.RETRY_ORGSTOKEN_DATA.url = /sc/auth/intgrt/consents/dtrmntn/retry
mydata.api.RETRY_ORGSTOKEN_DATA.method = POST
mydata.api.RETRY_ORGSTOKEN_DATA.host=

#설정 - 서비스탈퇴 API
mydata.api.REVOKE_DATA.url = /sc/auth/revoke
mydata.api.REVOKE_DATA.method = POST
mydata.api.REVOKE_DATA.host=

#이용 - 개별인증 제공기관 리스트 선택(인가코드 요청) API
mydata.api.OAUTHAUTHORIZE_DATA.url = /sc/auth/authorize
mydata.api.OAUTHAUTHORIZE_DATA.method = POST
mydata.api.OAUTHAUTHORIZE_DATA.host=

#이용 - 개별인증 종료(토큰 발급 요청) API
mydata.api.OAUTHTOKEN_DATA.url = /sc/auth/token
mydata.api.OAUTHTOKEN_DATA.method = POST
mydata.api.OAUTHTOKEN_DATA.host=

#메인 - 타행스크래핑  API
mydata.api.SCRAPINGACCOUNTS_DATA.url = /sc/scraping/accounts
mydata.api.SCRAPINGACCOUNTS_DATA.method = POST
mydata.api.SCRAPINGACCOUNTS_DATA.host=

#메인 - 실시간계좌조회 API
mydata.api.SCRAPINGTRANSACTIONS_DATA.url = /sc/scraping/accounts/transactions
mydata.api.SCRAPINGTRANSACTIONS_DATA.method = POST
mydata.api.SCRAPINGTRANSACTIONS_DATA.host=

#메인 - 거래고유번호로 ORG CD 조회 API
mydata.api.AUTHOFFER_DATA.url = /sc/auth/offer
mydata.api.AUTHOFFER_DATA.method = POST
mydata.api.AUTHOFFER_DATA.host=


#개별전송 (임시 추가 추후 삭제 필요)
mydata.api.personlSend_DATA.url = /sc/auth/intgrt/consents/trnsmt
mydata.api.personlSend_DATA.method = POST
mydata.api.personlSend_DATA.host=

#은행계좌목록조회
mydata.api.BANKACCOUNTLIST_DATA.url = /sc/use/bank/list
mydata.api.BANKACCOUNTLIST_DATA.method = POST
mydata.api.BANKACCOUNTLIST_DATA.host=

#카드목록조회
mydata.api.CARDLIST_DATA.url = /sc/use/card/cardOrgCardList
mydata.api.CARDLIST_DATA.method = POST
mydata.api.CARDLIST_DATA.host=

#카드상세조회
mydata.api.CARDDETAIL_DATA.url = /sc/use/card/cardList
mydata.api.CARDDETAIL_DATA.method = POST
mydata.api.CARDDETAIL_DATA.host=

#카드거래내역조회
mydata.api.CARDTRAN_DATA.url = /sc/use/card/cardTran
mydata.api.CARDTRAN_DATA.method = POST
mydata.api.CARDTRAN_DATA.host=

#카드리볼빙내역조회
mydata.api.CARDRVLVNG_DATA.url = /sc/use/card/cardRvlvng
mydata.api.CARDRVLVNG_DATA.method = POST
mydata.api.CARDRVLVNG_DATA.host=

#카드단기대출내역조회
mydata.api.CARDSHORTTRMLOAN_DATA.url = /sc/use/card/cardShortTrmLoan
mydata.api.CARDSHORTTRMLOAN_DATA.method = POST
mydata.api.CARDSHORTTRMLOAN_DATA.host=

#카드장기대출내역조회
mydata.api.CARDLONGTRMLOAN_DATA.url = /sc/use/card/cardLongTrmLoan
mydata.api.CARDLONGTRMLOAN_DATA.method = POST
mydata.api.CARDLONGTRMLOAN_DATA.host=

#카드장기대출거래내역조회
mydata.api.CARDLONGTRMLOANTRAN_DATA.url = /sc/use/card/cardLongTrmLoanTran
mydata.api.CARDLONGTRMLOANTRAN_DATA.method = POST
mydata.api.CARDLONGTRMLOANTRAN_DATA.host=

#카드기본정보조회
mydata.api.CARDBASICINFOR_DATA.url = /sc/use/card/detail
mydata.api.CARDBASICINFOR_DATA.method = POST
mydata.api.CARDBASICINFOR_DATA.host=

#금융투자목록조회
mydata.api.INVESTLIST_DATA.url = /sc/use/invest/investList
mydata.api.INVESTLIST_DATA.method = POST
mydata.api.INVESTLIST_DATA.host=

#금융투자기본정보조회
mydata.api.INVESTDFLT_DATA.url = /sc/use/invest/investDflt
mydata.api.INVESTDFLT_DATA.method = POST
mydata.api.INVESTDFLT_DATA.host=

#금융투자투자내역조회
mydata.api.INVESTINVESTER_DATA.url = /sc/use/invest/investInvester
mydata.api.INVESTINVESTER_DATA.method = POST
mydata.api.INVESTINVESTER_DATA.host=

#금융투자거래내역조회
mydata.api.INVESTTRANS_DATA.url = /sc/use/invest/investTrans
mydata.api.INVESTTRANS_DATA.method = POST
mydata.api.INVESTTRANS_DATA.host=

#금융투자상세정보조회
mydata.api.INVESTDETAIL_DATA.url = /sc/use/invest/investDetail
mydata.api.INVESTDETAIL_DATA.method = POST
mydata.api.INVESTDETAIL_DATA.host=

#금융투자자동이체정보조회
mydata.api.INVESTSCDUL_DATA.url = /sc/use/invest/scdul
mydata.api.INVESTSCDUL_DATA.method = POST
mydata.api.INVESTSCDUL_DATA.host=

#보험목록조회
mydata.api.INSURANCES_DATA.url = /sc/use/insurances/insurancesList
mydata.api.INSURANCES_DATA.method = POST
mydata.api.INSURANCES_DATA.host=

#보험목록조회
mydata.api.INSURANCES_DATA.url = /sc/use/insurances/insurancesList
mydata.api.INSURANCES_DATA.method = POST
mydata.api.INSURANCES_DATA.host=

#일반보험 기본정보조회
mydata.api.INSURANCES_DFLT.url = /sc/use/insurances/insurancesDflt
mydata.api.INSURANCES_DFLT.method = POST
mydata.api.INSURANCES_DFLT.host=

#일반보험 특약정보조회
mydata.api.INSURANCES_SPCL.url = /sc/use/insurances/insurancesSpcl
mydata.api.INSURANCES_SPCL.method = POST
mydata.api.INSURANCES_SPCL.host=

#일반보험 거래내역조회
mydata.api.INSURANCES_TRAN.url = /sc/use/insurances/insurancesTran
mydata.api.INSURANCES_TRAN.method = POST
mydata.api.INSURANCES_TRAN.host=

#자동차보험 기본정보조회
mydata.api.CARINSURANCES_DFLT.url = /sc/use/insurances/insurancesCarDflt
mydata.api.CARINSURANCES_DFLT.method = POST
mydata.api.CARINSURANCES_DFLT.host=

#자동차보험 거래내역조회  
mydata.api.CARINSURANCES_TRAN.url = /sc/use/insurances/insurancesCarTran
mydata.api.CARINSURANCES_TRAN.method = POST
mydata.api.CARINSURANCES_TRAN.host=


#피보험자보험 기본정보조회
mydata.api.INSURED_DFLT.url = /sc/use/insuredDflt
mydata.api.INSURED_DFLT.method = POST
mydata.api.INSURED_DFLT.host=

#피보험자 자동차보험 기본정보조회
mydata.api.CARINSURED_DFLT.url = /sc/use/insuredCarDflt
mydata.api.CARINSURED_DFLT.method = POST
mydata.api.CARINSURED_DFLT.host=

#피보험자보험 특약정보조회
mydata.api.INSURED_SPCL.url = /sc/use/insured/insuredSpcl
mydata.api.INSURED_SPCL.method = POST
mydata.api.INSURED_SPCL.host=

#피보험자보험 보장정보조회
mydata.api.INSURED_PROTECT.url = /sc/use/insured/insuredGrnt
mydata.api.INSURED_PROTECT.method = POST
mydata.api.INSURED_PROTECT.host=

#물, 일반보험 기본정보조회
mydata.api.INSURANCESGNRL_DFLT.url = /sc/use/insurances/generalDflt
mydata.api.INSURANCESGNRL_DFLT.method = POST
mydata.api.INSURANCESGNRL_DFLT.host=

#물, 일반보험 특약정보조회
mydata.api.INSURANCESGNRL_SPCL.url = /sc/use/insurances/generalSpcl
mydata.api.INSURANCESGNRL_SPCL.method = POST
mydata.api.INSURANCESGNRL_SPCL.host=

#물, 일반보험 보장정보조회
mydata.api.INSURANCESGNRL_PROTECT.url = /sc/use/insurances/generalGrnt
mydata.api.INSURANCESGNRL_PROTECT.method = POST
mydata.api.INSURANCESGNRL_PROTECT.host=

#물, 일반보험 거래내역조회
mydata.api.INSURANCESGNRL_TRAN.url = /sc/use/insurances/generalTran
mydata.api.INSURANCESGNRL_TRAN.method = POST
mydata.api.INSURANCESGNRL_TRAN.host=

#피보험자 물, 일반보험 기본정보조회
mydata.api.INSUREDGNRL_DFLT.url = /sc/use/insured/generalDflt
mydata.api.INSUREDGNRL_DFLT.method = POST
mydata.api.INSUREDGNRL_DFLT.host=

#피보험자 물, 일반보험 특약정보조회
mydata.api.INSUREDGNRL_SPCL.url = /sc/use/insured/generalSpcl
mydata.api.INSUREDGNRL_SPCL.method = POST
mydata.api.INSUREDGNRL_SPCL.host=

#피보험자 물, 일반보험 보장정보조회
mydata.api.INSUREDGNRL_PROTECT.url = /sc/use/insured/generalGrnt
mydata.api.INSUREDGNRL_PROTECT.method = POST
mydata.api.INSUREDGNRL_PROTECT.host=



#대출 기본정보조회
mydata.api.LOANINSURANCES_DFLT.url = /sc/use/insurances/insurancesLoanDflt
mydata.api.LOANINSURANCES_DFLT.method = POST
mydata.api.LOANINSURANCES_DFLT.host=

#대출 거래내역조회
mydata.api.LOANINSURANCES_TRAN.url = /sc/use/insurances/insurancesLoanTran
mydata.api.LOANINSURANCES_TRAN.method = POST
mydata.api.LOANINSURANCES_TRAN.host=

#보험 보장내역조회  
mydata.api.INSURANCES_PROTECT.url = /sc/use/insurances/insurancesGrnt
mydata.api.INSURANCES_PROTECT.method = POST
mydata.api.INSURANCES_PROTECT.host=

#은행계좌 상세조회
mydata.api.BANKACCOUNTDETAIL_DATA.url = /sc/use/bank/detail
mydata.api.BANKACCOUNTDETAIL_DATA.method = POST
mydata.api.BANKACCOUNTDETAIL_DATA.host=

#은행계좌 거래내역조회
mydata.api.BANKACCOUNTTRAN_DATA.url = /sc/use/bank/trans
mydata.api.BANKACCOUNTTRAN_DATA.method = POST
mydata.api.BANKACCOUNTTRAN_DATA.host=

#은행계좌 투자내역조회
mydata.api.BANKACCOUNTINVESTER_DATA.url = /sc/use/bank/invest
mydata.api.BANKACCOUNTINVESTER_DATA.method = POST
mydata.api.BANKACCOUNTINVESTER_DATA.host=

#은행계좌 자동이체 등록정보
mydata.api.BANKACCOUNTSCDUL_DATA.url = /sc/use/bank/scdul
mydata.api.BANKACCOUNTSCDUL_DATA.method = POST
mydata.api.BANKACCOUNTSCDUL_DATA.host=

#기타목록조회(할부금융)
mydata.api.CAPITALLIST_DATA.url = /sc/use/capital/list
mydata.api.CAPITALLIST_DATA.method = POST
mydata.api.CAPITALLIST_DATA.host=

#기타목록조회(통신)
mydata.api.TELECOMELIST_DATA.url = /sc/use/telecom/list
mydata.api.TELECOMELIST_DATA.method = POST
mydata.api.TELECOMELIST_DATA.host=

#기타목록 거래내역조회(할부금융)
mydata.api.CAPITALTRANS_DATA.url = /sc/use/capital/trans
mydata.api.CAPITALTRANS_DATA.method = POST
mydata.api.CAPITALTRANS_DATA.host=

#기타목록거래내역 조회(통신)
mydata.api.TELECOMETRANS_DATA.url = /sc/use/telecom/trans
mydata.api.TELECOMETRANS_DATA.method = POST
mydata.api.TELECOMETRANS_DATA.host=

#기타목록상세조회(할부금융)
mydata.api.CAPITALDETAIL_DATA.url = /sc/use/capital/detail
mydata.api.CAPITALDETAIL_DATA.method = POST
mydata.api.CAPITALDETAIL_DATA.host=

#기타목록 상세조회(통신)
mydata.api.TELECOMEDETAIL_DATA.url = /sc/use/telecom/detail
mydata.api.TELECOMEDETAIL_DATA.method = POST
mydata.api.TELECOMEDETAIL_DATA.host=

#전자금융 목록조회
mydata.api.USEEFINLIST_DATA.url = /sc/use/efin/list
mydata.api.USEEFINLIST_DATA.method = POST
mydata.api.USEEFINLIST_DATA.host=

#전자금융 거래내역 조회
mydata.api.USEEFINTRANS_DATA.url = /sc/use/efin/trans
mydata.api.USEEFINTRANS_DATA.method = POST
mydata.api.USEEFINTRANS_DATA.host=

#전자금융 상세조회
mydata.api.USEEFINDETAIL_DATA.url = /sc/use/efin/detail
mydata.api.USEEFINDETAIL_DATA.method = POST
mydata.api.USEEFINDETAIL_DATA.host=

#IRP 상세조회
mydata.api.IRPDETAIL_DATA.url = /sc/use/irp/dtl
mydata.api.IRPDETAIL_DATA.method = POST
mydata.api.IRPDETAIL_DATA.host=

#IRP 투자내역조회
mydata.api.IRPINVESTER_DATA.url = /sc/use/irp/invest
mydata.api.IRPINVESTER_DATA.method = POST
mydata.api.IRPINVESTER_DATA.host=

#IRP 거래내역조회
mydata.api.IRPTRANS_DATA.url = /sc/use/irp/tran
mydata.api.IRPTRANS_DATA.method = POST
mydata.api.IRPTRANS_DATA.host=

#개별인증 동의
mydata.api.CRDTINFOZINAGRMNT_DATA.url = /sc/auth/crdtinfoInAgrmnt
mydata.api.CRDTINFOZINAGRMNT_DATA.method = POST
mydata.api.CRDTINFOZINAGRMNT_DATA.host=

#가입유무 조회
mydata.api.REGISTYN_DATA.url = /sc/auth/entrncFlg
mydata.api.REGISTYN_DATA.method = POST
mydata.api.REGISTYN_DATA.host=

#개인신용정보 삭제
mydata.api.AUTHDELETE_DATA.url = /sc/auth/delete
mydata.api.AUTHDELETE_DATA.method = POST
mydata.api.AUTHDELETE_DATA.host=

#이용공통 - 이용약관동의
mydata.api.AGRMNT_DATA.url = /sc/auth/mydata/agrmnt
mydata.api.AGRMNT_DATA.method = POST
mydata.api.AGRMNT_DATA.host=

#공공 사업자등록증/폐업사실증명/휴업사실증명
mydata.api.REGISTINFOLIST_DATA.url = /api/v1/cpbb/common/pub/regist/infoList
mydata.api.REGISTINFOLIST_DATA.method = POST
mydata.api.REGISTINFOLIST_DATA.host=

#공공 부가가치세과세표준증명Receive
mydata.api.TAXRECEIVEINFO_DATA.url = /api/v1/cpbb/common/pub/tax/taxReceiveInfo
mydata.api.TAXRECEIVEINFO_DATA.method = POST
mydata.api.TAXRECEIVEINFO_DATA.host=

#공공 부가가치세과세표준증명Loan
mydata.api.TAXLOANINFO_DATA.url = /api/v1/cpbb/common/pub/tax/taxLoanInfo
mydata.api.TAXLOANINFO_DATA.method = POST
mydata.api.TAXLOANINFO_DATA.host=

#공공 건강보험자격득실확인서Receive
mydata.api.HLTHRECEIVEINFO_DATA.url = /api/v1/cpbb/common/pub/hlth/hlthReceiveInfo
mydata.api.HLTHRECEIVEINFO_DATA.method = POST
mydata.api.HLTHRECEIVEINFO_DATA.host=

#공공 건강보험자격득실확인서Card
mydata.api.HLTHCARDINFO_DATA.url = /api/v1/cpbb/common/pub/hlth/hlthCardInfo
mydata.api.HLTHCARDINFO_DATA.method = POST
mydata.api.HLTHCARDINFO_DATA.host=

#공공 건강보험자격득실확인서Loan
mydata.api.HLTHLOANINFO_DATA.url = /api/v1/cpbb/common/pub/hlth/hlthLoanInfo
mydata.api.HLTHLOANINFO_DATA.method = POST
mydata.api.HLTHLOANINFO_DATA.host=

#공공 건강보험납부확인서Receive
mydata.api.MDCLRECEIVELIST_DATA.url = /api/v1/cpbb/common/pub/mdcl/mdclReceiveList
mydata.api.MDCLRECEIVELIST_DATA.method = POST
mydata.api.MDCLRECEIVELIST_DATA.host=

#공공 건강보험납부확인서Card
mydata.api.MDCLCARDLIST_DATA.url = /api/v1/cpbb/common/pub/mdcl/mdclCardList
mydata.api.MDCLCARDLIST_DATA.method = POST
mydata.api.MDCLCARDLIST_DATA.host=

#공공 건강보험납부확인서Loan
mydata.api.MDCLLOANLIST_DATA.url = /api/v1/cpbb/common/pub/mdcl/mdclLoanList
mydata.api.MDCLLOANLIST_DATA.method = POST
mydata.api.MDCLLOANLIST_DATA.host=

#공공 주민등록초본
mydata.api.RSDNTINFO_DATA.url = /api/v1/cpbb/common/pub/rsdnt/rsdntInfo
mydata.api.RSDNTINFO_DATA.method = POST
mydata.api.RSDNTINFO_DATA.host=

#공공 사업자등록증명
mydata.api.CERTINFO_DATA.url = /api/v1/cpbb/common/pub/cert/certInfo
mydata.api.CERTINFO_DATA.method = POST
mydata.api.CERTINFO_DATA.host=

#공공 납세증명서
mydata.api.NTNLINFO_DATA.url = /api/v1/cpbb/common/pub/ntnl/ntnlInfo
mydata.api.NTNLINFO_DATA.method = POST
mydata.api.NTNLINFO_DATA.host=

#공공 소득금액증명
mydata.api.INCOMELIST_DATA.url = /api/v1/cpbb/common/pub/income/incomeList
mydata.api.INCOMELIST_DATA.method = POST
mydata.api.INCOMELIST_DATA.host=

#공공 공무원연금공단  (/sc/pension/pensionLoanInfo)
mydata.api.PENSION_DATA.url = /api/v1/cpbb/common/pub/pension/pensionLoanInfo
mydata.api.PENSION_DATA.method = POST
mydata.api.PENSION_DATA.host=

#마이데이터 연결이력 조회
mydata.api.CONNHISTLIST_DATA.url = /sc/auth/crdtinfoin/hist
mydata.api.CONNHISTLIST_DATA.method = POST
mydata.api.CONNHISTLIST_DATA.host=

#마이데이터 현대카드 최근5일 결제금액 조회
mydata.api.HYUNDAICARD_FIVEDAYS_DATA.url = /sc/use/card/hyundai/fivedays
mydata.api.HYUNDAICARD_FIVEDAYS_DATA.method = POST
mydata.api.HYUNDAICARD_FIVEDAYS_DATA.host=

#마이데이터 현대카드 최근3개월 결제금액 조회
mydata.api.HYUNDAICARD_THREEMONTH_DATA.url = /sc/use/card/hyundai/threeMonth
mydata.api.HYUNDAICARD_THREEMONTH_DATA.method = POST
mydata.api.HYUNDAICARD_THREEMONTH_DATA.host=

#마이데이터 지난달 가장많이쓴 가맹점(금액) 조회
mydata.api.HYUNDAICARD_LASTMONTH_DATA.url = /sc/use/card/hyundai/lastMonth
mydata.api.HYUNDAICARD_LASTMONTH_DATA.method = POST
mydata.api.HYUNDAICARD_LASTMONTH_DATA.host=

#마이데이터 선택동의서 마케팅 동의
mydata.api.SELECT_AGR.url = /sc/auth/slctagrmr
mydata.api.SELECT_AGR.method = POST
mydata.api.SELECT_AGR.host=

#비과세종합저축 관련 우대사항확인(MDS0007931)
mydata.api.PRFRNCLCASECNFRM_DATA.url = /api/v1/cpbb/common/pub/receive/prfrnclCaseCnfrm
mydata.api.PRFRNCLCASECNFRM_DATA.method = POST
mydata.api.PRFRNCLCASECNFRM_DATA.host=

#마이데이터 가입현황 통합조회
mydata.api.MGMTSSIGNUP_DATA.url = /sc/use/mgmts/signup
mydata.api.MGMTSSIGNUP_DATA.method = POST
mydata.api.MGMTSSIGNUP_DATA.host=

#제3자 제고 동의내역 요청
mydata.api.MGMTSAGREMENTS_DATA.url = /sc/use/mgmts/agrements/mydata
mydata.api.MGMTSAGREMENTS_DATA.method = POST
mydata.api.MGMTSAGREMENTS_DATA.host=

#제3자 제고 동의에 따른 제공내역요청
mydata.api.MGMTSAGREMENTSDETAIL_DATA.url = /sc/use/mgmts/agrements/detail/mydata
mydata.api.MGMTSAGREMENTSDETAIL_DATA.method = POST
mydata.api.MGMTSAGREMENTSDETAIL_DATA.host=

#숨은금융
mydata.api.SLEEPACCOUNTLIST_DATA.url = /sc/use/sleepNoncont/deposit
mydata.api.SLEEPACCOUNTLIST_DATA.method = POST
mydata.api.SLEEPACCOUNTLIST_DATA.host=

#숨은금융- 보험
mydata.api.SLEEPACCOUNTINSULIST_DATA.url = /sc/use/sleepNoncont/insu
mydata.api.SLEEPACCOUNTINSULIST_DATA.method = POST
mydata.api.SLEEPACCOUNTINSULIST_DATA.host=
