###########
# 추천서버 API
###########

rec.api.baseUrl=https://apiinttest.standardcharteredad.co.kr:8443
rec.api.timeout=20000

rec.api.token.clientId=MB
rec.api.token.clientSecret=MB_Secret
rec.api.token.grantType=client_credentials
rec.api.token.scope=resource.WRITE resource.READ
rec.api.token.service=rec
rec.api.token.connectLoc=UT

# 토큰발급
rec.api.token.url=/rec/oauth2/token

# 고객별추천아이템제공
rec.api.recommend.url=/rec/v1/common/recommend

# 벤또
rec.api.bento.url=/rec/v1/common/bento
