package com.scbank.process.api.svc.common.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.scbank.process.api.edmi.dto.mci.MciIbEdms001Res;
import com.scbank.process.api.edmi.dto.oltp.CbIbk01H38100Res;
import com.scbank.process.api.edmi.dto.oltp.CbIbk01H38300Res;
import com.scbank.process.api.edmi.dto.oltp.CbIbk01H38400Res;
import com.scbank.process.api.edmi.dto.oltp.CbIbk01H38500Res;
import com.scbank.process.api.edmi.dto.oltp.CbIbk01H38600Res;
import com.scbank.process.api.svc.common.dao.dto.AddCntrctDocument;
import com.scbank.process.api.svc.common.dao.dto.AddCntrctDocumentResult;
import com.scbank.process.api.svc.common.service.support.dto.contractdocument.SupDocListApplyResponse;
import com.scbank.process.api.svc.common.service.support.dto.contractdocument.SupDocListCardResponse;
import com.scbank.process.api.svc.common.service.support.dto.contractdocument.SupDocListDepositAndWithdrawalResponse;
import com.scbank.process.api.svc.common.service.support.dto.contractdocument.SupDocListForeignResponse;
import com.scbank.process.api.svc.common.service.support.dto.contractdocument.SupDocListFundRequestResponse;
import com.scbank.process.api.svc.common.service.support.dto.contractdocument.SupDocListFundResponse;
import com.scbank.process.api.svc.common.service.support.dto.contractdocument.SupDocListTrustAccountResponse;

@Mapper(componentModel = "spring")
public interface SupportContractDocumentMapper {

    @Mapping(source = "DUMMY_TEMP1", target = "dummyTemp1")
    @Mapping(source = "RESCODE", target = "resCode")
    @Mapping(source = "BODY_LENGTH", target = "bodyLength")
    @Mapping(source = "AOMACRONM", target = "aomacroNm")
    @Mapping(source = "ROWCOUNT", target = "rowCount")
    @Mapping(source = "DOCULIST", target = "docuList")
    public SupDocListFundRequestResponse toFundRequest(MciIbEdms001Res res);

    @Mapping(source = "ELEMENT_ID", target = "elementId")
    @Mapping(source = "TRAN_DT", target = "tranDt")
    @Mapping(source = "LOAN_REQ_NO", target = "loanReqNo")
    @Mapping(source = "ACCT_NO", target = "acctNo")
    @Mapping(source = "CUST_SSN", target = "custSsn")
    @Mapping(source = "DOC_CODE", target = "docCode")
    @Mapping(source = "DOC_NAME", target = "docName")
    @Mapping(source = "BRCH_NO", target = "brchNo")
    @Mapping(source = "EMP_NO", target = "empNo")
    @Mapping(source = "CHNNL_MK", target = "chnnlMk")
    @Mapping(source = "JOB_MK", target = "jobMk")
    @Mapping(source = "CREATE_DOC_DT", target = "createDocDt")
    public SupDocListFundRequestResponse.DOCU toDocumentResults(MciIbEdms001Res.DOCU mciObj);

    @Mapping(source = "YOBRNO", target = "yoBRNO")
    @Mapping(source = "YOKMCD", target = "yoKMCD")
    @Mapping(source = "YOBUNHO", target = "yoBUNHO")
    @Mapping(source = "YOSINIL", target = "yoSINIL")
    @Mapping(source = "YOGRGB", target = "yoGRGB")
    @Mapping(source = "YOLASIL", target = "yoLASIL")
    @Mapping(source = "YODOCGB", target = "yoDOCGB")
    @Mapping(source = "YOHPNO", target = "yoHPNO")
    @Mapping(source = "YOEMAIL", target = "yoEMAIL")
    @Mapping(source = "YOZONG", target = "yoZONG")
    @Mapping(source = "YOPRDNM", target = "yoPRDNM")
    @Mapping(source = "YOCUSNM", target = "yoCUSNM")
    @Mapping(source = "YOSGJAN", target = "yoSGJAN")
    @Mapping(source = "YOGAIPJA", target = "yoGAIPJA")
    @Mapping(source = "YOSWHAN", target = "yoSWHAN")
    @Mapping(source = "YOTBGJL", target = "yoTBGJL")
    @Mapping(source = "YOBSJUM", target = "yoBSJUM")
    @Mapping(source = "YOMANIL", target = "yoMANIL")
    @Mapping(source = "YOIYUL", target = "yoIYUL")
    @Mapping(source = "YOMANGJ", target = "yoMANGJ")
    @Mapping(source = "YOMANTJ", target = "yoMANTJ")
    @Mapping(source = "YOIJAGB", target = "yoIJAGB")
    @Mapping(source = "YOJYCGB", target = "yoJYCGB")
    @Mapping(source = "YOGAYAK", target = "yoGAYAK")
    @Mapping(source = "YOSAVGB", target = "yoSAVGB")
    @Mapping(source = "YOJYTJ", target = "yoJYTJ")
    @Mapping(source = "YOITDC", target = "yoITDC")
    @Mapping(source = "YOURL", target = "yoURL")
    @Mapping(source = "YOBUGUM", target = "yoBUGUM")
    @Mapping(source = "YOBPYN", target = "yoBPYN")
    @Mapping(source = "YODUMMY", target = "yoDUMMY")
    public SupDocListDepositAndWithdrawalResponse toDepositAndWithdrawal(CbIbk01H38500Res res);

    public List<AddCntrctDocument> toCntrctDocumentList(
            List<AddCntrctDocumentResult> list);

    @Mapping(source = "YOGRGB", target = "yoGRGB")
    @Mapping(source = "YOBRNO", target = "yoBRNO")
    @Mapping(source = "YOKMCD", target = "yoKMCD")
    @Mapping(source = "YOBUNHO", target = "yoBUNHO")
    @Mapping(source = "YOCIFNO", target = "yoCIFNO")
    @Mapping(source = "YOCNAME", target = "yoCNAME")
    @Mapping(source = "YOOPEIL", target = "yoOPEIL")
    @Mapping(source = "YOTOCD", target = "yoTOCD")
    @Mapping(source = "YOSINAK", target = "yoSINAK")
    @Mapping(source = "YOPRID", target = "yoPRID")
    @Mapping(source = "YOPNAME", target = "yoPNAME")
    @Mapping(source = "YOCRISK", target = "yoCRISK")
    @Mapping(source = "YOPRISK", target = "yoPRISK")
    @Mapping(source = "YOJAJUM", target = "yoJAJUM")
    @Mapping(source = "YOJAKM", target = "yoJAKM")
    @Mapping(source = "YOJABUN", target = "yoJABUN")
    @Mapping(source = "YOWBIL", target = "yoWBIL")
    @Mapping(source = "YOUNGB", target = "yoUNGB")
    @Mapping(source = "YOSUGB", target = "yoSUGB")
    @Mapping(source = "YOALGB", target = "yoALGB")
    @Mapping(source = "YOZONG", target = "yoZONG")
    @Mapping(source = "YOYSPCD", target = "yoYSPCD")
    @Mapping(source = "YOHANDO", target = "yoHANDO")
    @Mapping(source = "YOGRBB", target = "yoGRBB")
    @Mapping(source = "YOBSJUM", target = "yoBSJUM")
    @Mapping(source = "YOTOGB", target = "yoTOGB")
    @Mapping(source = "YOGIGAN", target = "yoGIGAN")
    @Mapping(source = "YOPBOSU", target = "yoPBOSU")
    @Mapping(source = "YOGBOSU", target = "yoGBOSU")
    @Mapping(source = "YOJDSSR", target = "yoJDSSR")
    @Mapping(source = "YOBSGB", target = "yoBSGB")
    @Mapping(source = "YOURL", target = "yoURL")
    @Mapping(source = "YOTONM", target = "yoTONM")
    @Mapping(source = "YOWJAGB", target = "yoWJAGB")
    @Mapping(source = "YOWJAJUM", target = "yoWJAJUM")
    @Mapping(source = "YOWJAKM", target = "yoWJAKM")
    @Mapping(source = "YOWJABUN", target = "yoWJABUN")
    @Mapping(source = "YOWJAIL", target = "yoWJAIL")
    @Mapping(source = "YOWJAAMT", target = "yoWJAAMT")
    @Mapping(source = "YOWSTIL", target = "yoWSTIL")
    @Mapping(source = "YOWLTIL", target = "yoWLTIL")
    @Mapping(source = "YOFDSPYH", target = "yoFDSPYH")
    @Mapping(source = "YOJHYB", target = "yoJHYB")
    @Mapping(source = "YOBCODE", target = "yoBCODE")
    @Mapping(source = "YOBD2DC", target = "yoBD2DC")
    public SupDocListTrustAccountResponse toTrustAccount(CbIbk01H38300Res res);

    @Mapping(source = "YOGRGB", target = "yoGRGB")
    @Mapping(source = "YOBRNO", target = "yoBRNO")
    @Mapping(source = "YOKMCD", target = "yoKMCD")
    @Mapping(source = "YOBUNHO", target = "yoBUNHO")
    @Mapping(source = "YOCIFNO", target = "yoCIFNO")
    @Mapping(source = "YOCNAME", target = "yoCNAME")
    @Mapping(source = "YOOPEIL", target = "yoOPEIL")
    @Mapping(source = "YOTOCD", target = "yoTOCD")
    @Mapping(source = "YOSINAK", target = "yoSINAK")
    @Mapping(source = "YOPRID", target = "yoPRID")
    @Mapping(source = "YOPNAME", target = "yoPNAME")
    @Mapping(source = "YOCRISK", target = "yoCRISK")
    @Mapping(source = "YOPRISK", target = "yoPRISK")
    @Mapping(source = "YOJAJUM", target = "yoJAJUM")
    @Mapping(source = "YOJAKM", target = "yoJAKM")
    @Mapping(source = "YOJABUN", target = "yoJABUN")
    @Mapping(source = "YOWBIL", target = "yoWBIL")
    @Mapping(source = "YOUNGB", target = "yoUNGB")
    @Mapping(source = "YOSUGB", target = "yoSUGB")
    @Mapping(source = "YOALGB", target = "yoALGB")
    @Mapping(source = "YOZONG", target = "yoZONG")
    @Mapping(source = "YOYSPCD", target = "yoYSPCD")
    @Mapping(source = "YOHANDO", target = "yoHANDO")
    @Mapping(source = "YOGRBB", target = "yoGRBB")
    @Mapping(source = "YOBSJUM", target = "yoBSJUM")
    @Mapping(source = "YOTOGB", target = "yoTOGB")
    @Mapping(source = "YOGIGAN", target = "yoGIGAN")
    @Mapping(source = "YOPBOSU", target = "yoPBOSU")
    @Mapping(source = "YOGBOSU", target = "yoGBOSU")
    @Mapping(source = "YOJDSSR", target = "yoJDSSR")
    @Mapping(source = "YOBSGB", target = "yoBSGB")
    @Mapping(source = "YOURL", target = "yoURL")
    @Mapping(source = "YOTONM", target = "yoTONM")
    @Mapping(source = "YOWJAGB", target = "yoWJAGB")
    @Mapping(source = "YOWJAJUM", target = "yoWJAJUM")
    @Mapping(source = "YOWJAKM", target = "yoWJAKM")
    @Mapping(source = "YOWJABUN", target = "yoWJABUN")
    @Mapping(source = "YOWJAIL", target = "yoWJAIL")
    @Mapping(source = "YOWJAAMT", target = "yoWJAAMT")
    @Mapping(source = "YOWSTIL", target = "yoWSTIL")
    @Mapping(source = "YOWLTIL", target = "yoWLTIL")
    @Mapping(source = "YOFDSPYH", target = "yoFDSPYH")
    @Mapping(source = "YOJHYB", target = "yoJHYB")
    @Mapping(source = "YOBCODE", target = "yoBCODE")
    @Mapping(source = "YOBD2DC", target = "yoBD2DC")
    public SupDocListFundResponse toFund(CbIbk01H38300Res res);

    @Mapping(source = "YOJHNM", target = "yoJHNM")
    @Mapping(source = "YOCDGB", target = "yoCDGB")
    @Mapping(source = "YOBKNM", target = "yoBKNM")
    @Mapping(source = "YOKJGJ", target = "yoKJGJ")
    @Mapping(source = "YOGJIL", target = "yoGJIL")
    @Mapping(source = "YOSINHD", target = "yoSINHD")
    @Mapping(source = "YODBGIL", target = "yoDBGIL")
    @Mapping(source = "YOSVCIY", target = "yoSVCIY")
    @Mapping(source = "YOHB1IY", target = "yoHB1IY")
    @Mapping(source = "YOHB2IY", target = "yoHB2IY")
    @Mapping(source = "YORVSIY", target = "yoRVSIY")
    @Mapping(source = "YOGJGB", target = "yoGJGB")
    @Mapping(source = "YOJGNM", target = "yoJGNM")
    @Mapping(source = "YOGIGAN", target = "yoGIGAN")
    @Mapping(source = "YOHMUPNO", target = "yoHMUPNO")
    @Mapping(source = "YOHMJSO1", target = "yoHMJSO1")
    @Mapping(source = "YOHMJSO2", target = "yoHMJSO2")
    @Mapping(source = "YOCARD", target = "yoCARD")
    @Mapping(source = "YOGYHWNO", target = "yoGYHWNO")
    @Mapping(source = "YOHNAME", target = "yoHNAME")
    @Mapping(source = "YOHJUMIN", target = "yoHJUMIN")
    @Mapping(source = "YOJHCD", target = "yoJHCD")
    @Mapping(source = "YOSVCGB", target = "yoSVCGB")
    @Mapping(source = "YOSVCHD", target = "yoSVCHD")
    public SupDocListCardResponse toCard(CbIbk01H38400Res res);

    @Mapping(source = "YOBRNO", target = "yoBRNO")
    @Mapping(source = "YOKMCD", target = "yoKMCD")
    @Mapping(source = "YOBUNHO", target = "yoBUNHO")
    @Mapping(source = "YOSINIL", target = "yoSINIL")
    @Mapping(source = "YOJUMIN", target = "yoJUMIN")
    @Mapping(source = "YOGRGB", target = "yoGRGB")
    @Mapping(source = "YOLASIL", target = "yoLASIL")
    @Mapping(source = "YODOCGB", target = "yoDOCGB")
    @Mapping(source = "YOHPNO", target = "yoHPNO")
    @Mapping(source = "YOEMAIL", target = "yoEMAIL")
    @Mapping(source = "YOZONG", target = "yoZONG")
    @Mapping(source = "YOPRDNM", target = "yoPRDNM")
    @Mapping(source = "YOCUSNM", target = "yoCUSNM")
    @Mapping(source = "YOSGJAN", target = "yoSGJAN")
    @Mapping(source = "YOGAIPJA", target = "yoGAIPJA")
    @Mapping(source = "YOTBGJL", target = "yoTBGJL")
    @Mapping(source = "YOBSJUM", target = "yoBSJUM")
    @Mapping(source = "YOMANIL", target = "yoMANIL")
    @Mapping(source = "YOIYUL", target = "yoIYUL")
    @Mapping(source = "YOMANGJ", target = "yoMANGJ")
    @Mapping(source = "YOMANTJ", target = "yoMANTJ")
    @Mapping(source = "YOCURCOD", target = "yoCURCOD")
    @Mapping(source = "YOCURNM", target = "yoCURNM")
    @Mapping(source = "YOTJAGB", target = "yoTJAGB")
    @Mapping(source = "YOITNET", target = "yoITNET")
    @Mapping(source = "YOGRUSE", target = "yoGRUSE")
    @Mapping(source = "YOJAGJR", target = "yoJAGJR")
    @Mapping(source = "YODEALJ", target = "yoDEALJ")
    @Mapping(source = "YOJUNGSO", target = "yoJUNGSO")
    @Mapping(source = "YOJSSGB", target = "yoJSSGB")
    @Mapping(source = "YOURL", target = "yoURL")
    @Mapping(source = "YOMNJGB", target = "yoMNJGB")
    public SupDocListForeignResponse toForeign(CbIbk01H38600Res res);

    @Mapping(source = "YOGUBUN", target = "yoGUBUN")
    @Mapping(source = "YONAME", target = "yoNAME")
    @Mapping(source = "YOJUMIN", target = "yoJUMIN")
    @Mapping(source = "YOGYECD", target = "yoGYECD")
    @Mapping(source = "YOJAGUM", target = "yoJAGUM")
    @Mapping(source = "YODAEGB", target = "yoDAEGB")
    @Mapping(source = "YOFSTIL", target = "yoFSTIL")
    @Mapping(source = "YOLASGI", target = "yoLASGI")
    @Mapping(source = "YOSNAMT", target = "yoSNAMT")
    @Mapping(source = "YOSPGB", target = "yoSPGB")
    @Mapping(source = "YOSPCOD", target = "yoSPCOD")
    @Mapping(source = "YOGYENM", target = "yoGYENM")
    @Mapping(source = "YOGEOHT", target = "yoGEOHT")
    @Mapping(source = "YOIYGBN", target = "yoIYGBN")
    @Mapping(source = "YORPWOL", target = "yoRPWOL")
    @Mapping(source = "YOJYIYL", target = "yoJYIYL")
    @Mapping(source = "YOGJIYL", target = "yoGJIYL")
    @Mapping(source = "YOGASAN", target = "yoGASAN")
    @Mapping(source = "YOUDIY01", target = "yoUDIY01")
    @Mapping(source = "YOUDIY02", target = "yoUDIY02")
    @Mapping(source = "YOUDIY03", target = "yoUDIY03")
    @Mapping(source = "YOUDIY04", target = "yoUDIY04")
    @Mapping(source = "YOUDIY05", target = "yoUDIY05")
    @Mapping(source = "YOUDIY06", target = "yoUDIY06")
    @Mapping(source = "YOUDIY07", target = "yoUDIY07")
    @Mapping(source = "YOUDIY08", target = "yoUDIY08")
    @Mapping(source = "YOUDIY09", target = "yoUDIY09")
    @Mapping(source = "YOUDIY10", target = "yoUDIY10")
    @Mapping(source = "YOUDIY11", target = "yoUDIY11")
    @Mapping(source = "YOUDIY12", target = "yoUDIY12")
    @Mapping(source = "YOUDIY13", target = "yoUDIY13")
    @Mapping(source = "YOUDIY14", target = "yoUDIY14")
    @Mapping(source = "YOUDIY15", target = "yoUDIY15")
    @Mapping(source = "YOUDIY16", target = "yoUDIY16")
    @Mapping(source = "YOHDUDY1", target = "yoHDUDY1")
    @Mapping(source = "YOHDUDY2", target = "yoHDUDY2")
    @Mapping(source = "YOHDUDY3", target = "yoHDUDY3")
    @Mapping(source = "YOICHIY", target = "yoICHIY")
    @Mapping(source = "YOICHRI", target = "yoICHRI")
    @Mapping(source = "YOSUIY1", target = "yoSUIY1")
    @Mapping(source = "YOSUIL1", target = "yoSUIL1")
    @Mapping(source = "YOSUIY2", target = "yoSUIY2")
    @Mapping(source = "YOSUIL2", target = "yoSUIL2")
    @Mapping(source = "YOSUIY3", target = "yoSUIY3")
    @Mapping(source = "YOSUIL3", target = "yoSUIL3")
    @Mapping(source = "YOSUGIJ", target = "yoSUGIJ")
    @Mapping(source = "YOMJEYN", target = "yoMJEYN")
    @Mapping(source = "YOYDYN", target = "yoYDYN")
    @Mapping(source = "YOCENIL", target = "yoCENIL")
    @Mapping(source = "YOICBUN", target = "yoICBUN")
    @Mapping(source = "YOSHCD", target = "yoSHCD")
    @Mapping(source = "YOGEOCI", target = "yoGEOCI")
    @Mapping(source = "YOSMSGB", target = "yoSMSGB")
    @Mapping(source = "YOTOAMT", target = "yoTOAMT")
    @Mapping(source = "YOSJAMT", target = "yoSJAMT")
    @Mapping(source = "YOIYDIS", target = "yoIYDIS")
    @Mapping(source = "YOHYUIL", target = "yoHYUIL")
    @Mapping(source = "YOYUNIY", target = "yoYUNIY")
    @Mapping(source = "YOSHGBN", target = "yoSHGBN")
    @Mapping(source = "YOISUGK", target = "yoISUGK")
    @Mapping(source = "YOISUCD", target = "yoISUCD")
    @Mapping(source = "YOILBAN", target = "yoILBAN")
    @Mapping(source = "YOSDJNM", target = "yoSDJNM")
    @Mapping(source = "YOIYFIX", target = "yoIYFIX")
    @Mapping(source = "YOSHGG", target = "yoSHGG")
    @Mapping(source = "YOISUYI", target = "yoISUYI")
    @Mapping(source = "YOBUGUM", target = "yoBUGUM")
    @Mapping(source = "YOCHAIL", target = "yoCHAIL")
    @Mapping(source = "YOBJSYU", target = "yoBJSYU")
    @Mapping(source = "YODCJAN", target = "yoDCJAN")
    @Mapping(source = "YOPAYJR", target = "yoPAYJR")
    @Mapping(source = "YORVKYN", target = "yoRVKYN")
    @Mapping(source = "YOSSUDY", target = "yoSSUDY")
    @Mapping(source = "YOSUAMT", target = "yoSUAMT")
    @Mapping(source = "YOINSU", target = "yoINSU")
    @Mapping(source = "YOJNDAE", target = "yoJNDAE")
    @Mapping(source = "YOBHIYL", target = "yoBHIYL")
    @Mapping(source = "YOBKIYL", target = "yoBKIYL")
    @Mapping(source = "YOSHBY", target = "yoSHBY")
    @Mapping(source = "YOPPWON", target = "yoPPWON")
    @Mapping(source = "YOJHYN", target = "yoJHYN")
    @Mapping(source = "YOMOAYL", target = "yoMOAYL")
    @Mapping(source = "YOGEYAK", target = "yoGEYAK")
    @Mapping(source = "YOMOVCD", target = "yoMOVCD")
    @Mapping(source = "YOBPYN", target = "yoBPYN")
    @Mapping(source = "YODUMMY", target = "yoDUMMY")
    @Mapping(source = "YOSUCNT", target = "yoSUCNT")
    @Mapping(source = "YOSUTBL", target = "yoSUTBL")
    public SupDocListApplyResponse toApply(CbIbk01H38100Res res);

    @Mapping(source = "YOSUGEJ", target = "yoSUGEJ")
    @Mapping(source = "YOSUNAM", target = "yoSUNAM")
    SupDocListApplyResponse.YOSUTBL toYOSUTBLApply(CbIbk01H38100Res.YOSUTBL res);
}
